# -*- coding: utf-8 -*-
# main_app/langs/ch.py

CHINESE_DICT = {
    # ── Main Interface ────────────────────────────────────────
    'main_title':          (1001, 'FDSB'),
    'no_bots_hint':        (1002, '未找到机器人。点击"新建机器人"来创建一个。'),
    'new_bot':             (1003, '新建机器人'),
    'discord':             (1004, 'Discord'),
    'github':              (1005, 'GitHub'),

    # ── Create Bot Window ─────────────────────────────────────
    'name_label':          (1006, '名称'),
    'token_label':         (1007, '令牌'),
    'name_hint':           (1008, '输入机器人名称'),
    'token_hint':          (1009, '输入机器人令牌'),
    'make':                (1010, '创建'),
    'image_label':         (1011, '图片'),
    'ok':                  (1012, '确定'),
    'token_required':      (1013, '令牌为必填项'),
    'name_taken':          (1014, '名称已被占用\n请选择其他名称'),
    'token_invalid_format':(1015, '令牌格式无效。'),

    # ── Bot Dashboard ─────────────────────────────────────────
    'state_server':        (1016, '服务器状态'),
    'online':              (1017, '在线'),
    'offline':             (1018, '离线'),
    'start':               (1019, '启动'),
    'stop':                (1020, '停止'),
    'starting':            (1021, '正在连接...'),
    'stopping':            (1022, '正在停止...'),
    'servers_count':       (1023, '服务器数量'),
    'whats_new':           (1024, '更新内容'),
    'no_updates':          (1025, '暂无可用更新。'),
    'no_file':             (1026, '未找到更新文件。'),
    'read_error':          (1027, '无法读取文件。'),
    'invite_bot':          (1028, '邀请机器人'),
    'back':                (1029, '返回'),
    'avatar_none':         (1030, '无头像'),

    # ── Navigation Tabs ───────────────────────────────────────
    'tab_main':            (1117, '主页'),
    'tab_commands':        (1118, '命令'),
    'tab_variables':       (1119, '变量'),
    'tab_settings':        (1120, '设置'),
    'tab_wiki':            (1121, '百科'),

    # ── Settings ──────────────────────────────────────────────
    'general_section':     (1031, '常规'),
    'design_section':      (1032, '外观'),
    'info_section':        (1033, '信息'),
    'name_project':        (1034, '项目名称'),
    'token_field':         (1035, '机器人令牌'),
    'bot_name_hint':       (1036, '机器人名称'),
    'bot_token_hint':      (1037, '机器人令牌'),
    'save':                (1038, '保存'),
    'language':            (1039, '语言'),
    'wiki':                (1040, '百科'),
    'link':                (1041, '(链接)'),
    'restart_notice':      (1042, '正在重启...'),
    'search_lang':         (1043, '搜索语言...'),
    'select_language':     (1044, '选择语言'),
    'selfbot_token_blocked': (1045, '出于安全考虑，严禁使用用户/自托管机器人令牌。'),
    'invalid_bot_token':   (1046, '机器人令牌无效。请输入官方 Discord 机器人令牌。'),

    # ── Export Data ───────────────────────────────────────────
    'export_section':      (1047, '导出数据'),
    'export_desc':         (1048, '将命令和变量导出为 ZIP 文件'),
    'export_zip':          (1049, '导出 ZIP'),
    'no_bot_selected':     (1050, '未选择机器人！'),
    'folders_not_found':   (1051, '未找到文件夹！'),
    'export_failed':       (1052, '导出失败！'),
    'export_success':      (1053, '导出成功！'),

    # ── Danger Zone / Delete ──────────────────────────────────
    'danger_zone':         (1054, '危险区域'),
    'delete_bot_perm':     (1055, '永久删除此机器人'),
    'captcha_enter':       (1056, '输入 3 位数字'),
    'captcha_hint':        (1057, '请输入上方显示的 3 位数字'),
    'confirm_delete':      (1058, '确认删除'),
    'captcha_wrong':       (1059, '验证码错误 — 请重试'),

    # ── Themes Names ──────────────────────────────────────────
    'system_wh':           (1060, '跟随系统（浅色）'),
    'system_da':           (1061, '跟随系统（深色）'),
    'blue_sky':            (1062, '蓝色 - 天空'),
    'yellow_bile':         (1063, '黄色 - 金色'),
    'v2_dark':             (1064, '暗金色'),

    # ── commands_view ─────────────────────────────────────────
    'commands_slash':      (1065, '/ 命令'),
    'info_command':        (1066, '命令信息'),
    'command_editor':      (1067, '命令编辑器'),
    'total_lines':         (1068, '行数'),
    'total_text':          (1069, '字符数'),
    'fdscript_hint':       (1070, '# 在此输入 FDScript 代码...'),
    'prefix_label':        (1071, '前缀'),
    'prefix_hint':         (1072, '例如：!cmd'),
    'search':              (1073, '搜索'),
    'commands':            (1074, '命令'),
    'no_cmds_hint':        (1075, '未找到命令。点击 + 创建一个。'),
    'del':                 (1076, '删除'),
    'name_required':       (1077, '名称为必填项'),
    'delete_q':            (1078, '要删除吗？'),
    'delete_confirm':      (1079, '确定要删除"{item_name}"吗？\n此操作无法撤销。'),
    'dest_event':          (1080, '事件'),
    'dest_cmd':            (1081, '命令'),
    'commands_label':      (1082, '输入命令名称'),
    'unsaved_title':       (1083, '未保存的更改'),
    'unsaved_body':        (1084, '存在未保存的更改。是否在退出前保存？'),
    'discard':             (1085, '放弃'),
    'loading':             (1086, '加载中...'),

    # ── wiki_view ─────────────────────────────────────────────
    'search_hint':          (1122, '搜索函数...'),
    'check_updates':        (1123, '检查更新'),
    'checking':             (1124, '正在检查...'),
    'downloading':          (1125, '正在下载百科...'),
    'up_to_date':           (1126, '百科已是最新版本 (v{v})'),
    'update_available':     (1127, '有新更新可用 (v{v})'),
    'update_failed':        (1128, '检查更新失败'),
    'no_cache':             (1129, '暂无本地数据。请点击"检查更新"。'),
    'no_results':           (1130, '无结果'),
    'function_info':        (1131, '函数信息'),
    'no_details':           (1132, '暂无详细信息'),
    'open_dashboard':       (1133, '打开控制面板'),
    'copy_syntax':          (1134, '复制'),
    'copied':               (1135, '已复制！'),
    'syntax':               (1136, '语法'),
    'parameters':           (1137, '参数'),
    'example':              (1138, '示例'),
    'notes':                (1139, '备注'),
    'warnings':             (1140, '警告'),
    'required':             (1141, '必需'),
    'optional':             (1142, '可选'),
    'not_used_in_bot':      (1143, '此机器人的命令中未使用此函数'),

    # ── wiki_view filters ─────────────────────────────────────
    'filter_all':           (1148, '全部'),
    'filter_command':       (1149, '命令'),
    'filter_event':         (1150, '事件'),
    'filter_variable':      (1171, '变量'),
    'filter_discord':       (1172, 'Discord'),
    'filter_time':          (1173, '时间'),
    'filter_other':         (1174, '其他'),
    'filter_title':         (1241, '分类'),
    'filter_tooltip':       (1246, '筛选'),
    'no_categories':        (1247, '暂无分类'),

    # ── wiki_view callouts ────────────────────────────────────
    'callout_note':         (1144, '提示'),
    'callout_limit':        (1145, '限制'),
    'callout_important':    (1146, '这很重要！'),
    'callout_question':     (1147, '这是什么？'),

    # ── variables_view ────────────────────────────────────────
    'variables':            (1028, '变量'),
    'variables_slash':      (1151, '变量 /'),
    'scoped_vars':          (1152, '按用户区分的值'),
    'value_label':          (1153, '值'),
    'var_name_hint':        (1154, '变量名'),
    'var_value_hint':       (1155, '变量值'),
    'info_var':             (1156, '变量信息'),
    'invalid_json':         (1157, 'JSON 无效'),
    'json_must_be_object':  (1158, '顶层值必须是一个 JSON 对象（{"userID": "value"}）。'),
    'no_variables':         (1089, '暂无变量'),
    'enter_variable_name':  (1106, '输入变量名'),

    # ── App Updater ───────────────────────────────────────────
    'app_update_title':           (1159, '有可用更新'),
    'app_update_new_version':     (1160, '新版本'),
    'app_update_current_version': (1161, '当前版本'),
    'app_update_no_changelog':    (1162, '此更新暂无更新日志。'),
    'app_update_later':           (1163, '稍后'),
    'app_update_now':             (1164, '立即更新'),
    'app_update_downloading':     (1165, '正在下载'),
    'app_update_done':            (1166, '下载完成 ✓'),
    'app_update_failed':          (1167, '下载失败'),
    'app_update_open_installer':  (1168, '打开安装程序'),
    'app_update_installer_opened':(1169, '安装程序已打开。完成安装后，请重新打开应用。'),
    'app_update_open_failed':     (1170, '无法打开安装程序文件'),

    # ── Status Bot View ───────────────────────────────────────
    'status_bot_section':         (1175, '机器人状态'),
    'status_bot_desc':            (1176, '配置机器人的在线状态和轮播状态消息'),
    'open_status_bot':            (1177, '管理状态'),
    'status_bot_title':           (1178, '状态机器人'),
    'sv_status_label':            (1179, '状态'),
    'sv_loop_time_label':         (1180, '循环时间'),
    'sv_loop_time_seconds':       (1181, '秒'),
    'sv_loop_time_hint':          (1182, '仅限整数，最小 12 秒'),
    'sv_activate_presence':       (1183, '启用机器人在线状态'),
    'sv_status_entries':          (1184, '状态条目'),
    'sv_add_entry':               (1185, '添加新条目'),
    'sv_entry_details_ph':        (1186, '状态详情'),
    'sv_status_online':           (1187, '在线'),
    'sv_status_idle':             (1188, '离开'),
    'sv_status_dnd':              (1189, '请勿打扰'),
    'sv_status_invisible':        (1190, '隐身'),
    'sv_create_edit_title':       (1191, '创建或编辑状态条目'),
    'sv_status_data':             (1192, '状态数据'),
    'sv_prefix_status':           (1193, '状态前缀'),
    'sv_status_field':            (1194, '状态'),
    'sv_status_details':          (1195, '状态详情'),
    'sv_prefix_hint':             (1196, '例如：正在玩'),
    'sv_status_hint':             (1197, '简短状态文本'),
    'sv_details_hint':            (1198, '状态下方显示的额外信息'),
    'sv_preview':                 (1199, '预览'),
    'sv_name_bot':                (1200, '机器人名称'),
    'sv_app_badge':               (1201, 'APP'),
    'sv_save_entry':              (1202, '保存条目'),
    'sv_back':                    (1203, '返回'),
    'sv_no_entries':              (1204, '暂无状态条目。'),
    'sv_unit_second':             (1205, '秒'),
    'sv_unit_minute':             (1206, '分钟'),
    'sv_unit_hour':               (1207, '小时'),
    'sv_unit_day':                (1208, '天'),
    'sv_loop_time_integer_error': (1209, '仅限整数 — 不允许小数或符号'),
    'sv_loop_time_min_error':     (1210, '循环时间不能少于 12 秒'),
    'sv_activity_type':           (1211, '活动类型'),
    'sv_activity_playing':        (1212, '正在玩'),
    'sv_activity_streaming':      (1213, '正在直播'),
    'sv_activity_listening':      (1214, '正在收听'),
    'sv_activity_watching':       (1215, '正在观看'),
    'sv_activity_competing':      (1216, '正在竞赛'),
    'sv_stream_url':              (1217, '直播链接'),
    'sv_stream_url_hint':         (1218, 'https://twitch.tv/... 或 https://youtube.com/...'),
    'sv_stream_url_required':     (1219, '直播状态需要提供直播链接'),
    'sv_stream_url_invalid':      (1220, '仅支持 Twitch 或 YouTube 链接'),
    'sv_help_note_title':         (1229, '备注'),
    'sv_help_note_body':          (1230, '更改需要一点时间才能生效。在机器人运行期间'
                                      '添加、编辑或删除状态，以及开启或关闭在线状态，'
                                      '都不会立即生效。机器人会先完成当前状态列表的轮播，'
                                      '因此更新可能需要一段时间才会显示。'),

    # ── Create Bot — Import from backup ────────────────────────────────────
    'import_zip_btn':           (1221, '从备份恢复'),
    'import_zip_disabled_hint': (1222, '请先设置机器人名称和有效令牌'),
    'import_zip_selected':      (1223, '已选择备份：{file_name}'),
    'import_zip_clear':         (1224, '移除'),
    'import_zip_invalid':       (1225, '这似乎不是机器人备份文件'),
    'import_zip_pick_title':    (1226, '选择备份 ZIP 文件'),
    'import_zip_applied':       (1227, '机器人已创建并恢复了备份！'),
    'import_zip_failed':        (1228, '机器人已创建，但恢复备份失败'),

    # ── General Actions & Feedback ─────────────────────────────────────────
    'edit':                   (1094, '编辑'),
    'delete':                 (1095, '删除'),
    'cancel':                 (1100, '取消'),
    'reset':                  (1242, '重置'),
    'close':                  (1243, '关闭'),
    'done':                   (1244, '完成'),
    'clear_search':           (1245, '清除搜索'),
    'saved_successfully':     (1231, '保存成功'),

    # ── Mobile Warning ────────────────────────────────────────────────────
    'mobile_warn_title':      (1232, '移动端后台运行提示'),
    'mobile_warn_body':       (1233, '在移动系统（仅限 Android）上运行机器人受到系统严格的后台限制。\n\n• 在最佳情况下，机器人最多只能在后台运行 6 小时。\n• 您必须在设备设置中关闭电池优化（设为"无限制"）。\n• 某些设备在应用最小化时可能会立即挂起机器人。\n\n目前尚不支持在主机/服务器/VPS 等环境上运行机器人。'),

    # ── Command Editor Syntax Warning ─────────────────────────────────────
    'syntax_warn_banner':     (1234, '颜色模式已启用。对于较大的文件（超过 2000 字符），请关闭颜色模式以避免设备卡顿。'),
    'syntax_limit_refusal':   (1235, '无法启用颜色模式：文本超过 2000 字符限制，为保证性能已禁用。'),
    'syntax_color_label':     (1236, '颜色'),

    # ── Total Counts ──────────────────────────────────────────────────────
    'total_bots_count':       (1237, '您拥有的机器人总数：{count}'),
    'total_vars_count':       (1238, '变量总数：{count}'),
    'total_cmds_count':       (1239, '命令总数：{count}'),
    'total_wiki_count':       (1240, '结果数：{count}'),

    # ── Token Verification ────────────────────────────────────────────────
    'verify_token':           (1248, '验证令牌'),
    'verifying':              (1249, '正在验证...'),
    'token_valid':            (1250, '连接成功！令牌有效。'),
    'token_invalid':          (1251, '令牌无效或连接失败。'),

    # ── Android Background Notification ────────────────────────────────────
    'fgs_state_working':          (1252, '机器人正在运行 | 🟢'),
    'server_status_online':       (1257, '服务器在线：{name}'),
    'server_status_stopped':      (1258, '服务器已停止'),
    'fgs_limit_reached':          (1259, '已达到 Android 后台运行上限（6 小时）。请打开应用以重新启动服务器。'),
    'fgs_start_failed':           (1260, '后台服务启动失败：{error}'),

    # ── Privileged Gateway Intents Warning ────────────────────────────────
    'intents_warning_title':      (1261, '特权网关意图未启用'),
    'intents_warning_msg':        (1262, '警告：特权网关意图（在线状态、成员、消息内容）尚未在 Discord 开发者门户中启用。命令和事件可能无法正常工作。'),
    'open_dev_portal':            (1263, '前往门户启用'),

    'syntax_switch_tooltip': (1264, '切换语法高亮'),
    'new_command_file':      (1265, 'New.fds'),
    'wiki_events_tooltip':   (1266, '百科：事件'),
    'new_variable_file':     (1267, 'new.json'),
    'scoped_json_title':     (1268, '{name} — 用户专属 JSON 数据'),
}