# -*- coding: utf-8 -*-
# main_app/langs/de.py

GERMAN_DICT = {
    # ── Main Interface ────────────────────────────────────────
    'main_title':          (1001, 'FDSB'),
    'no_bots_hint':        (1002, 'Keine Bots gefunden. Klicke auf "Neuer Bot", um einen zu erstellen.'),
    'new_bot':             (1003, 'Neuer Bot'),
    'discord':             (1004, 'Discord'),
    'github':              (1005, 'GitHub'),

    # ── Create Bot Window ─────────────────────────────────────
    'name_label':          (1006, 'Name'),
    'token_label':         (1007, 'Token'),
    'name_hint':           (1008, 'Bot-Namen eingeben'),
    'token_hint':          (1009, 'Bot-Token eingeben'),
    'make':                (1010, 'Erstellen'),
    'image_label':         (1011, 'Bild'),
    'ok':                  (1012, 'OK'),
    'token_required':      (1013, 'Token ist erforderlich'),
    'name_taken':          (1014, 'Name bereits vergeben\nWähle einen anderen Namen'),
    'token_invalid_format':(1015, 'Ungültiges Token-Format.'),

    # ── Bot Dashboard ─────────────────────────────────────────
    'state_server':        (1016, 'Serverstatus'),
    'online':              (1017, 'Online'),
    'offline':             (1018, 'Offline'),
    'start':               (1019, 'Starten'),
    'stop':                (1020, 'Stoppen'),
    'starting':            (1021, 'Verbindung wird hergestellt...'),
    'stopping':            (1022, 'Wird gestoppt...'),
    'servers_count':       (1023, 'Server'),
    'whats_new':           (1024, 'Neuigkeiten'),
    'no_updates':          (1025, 'Keine Updates verfügbar.'),
    'no_file':             (1026, 'Update-Datei nicht gefunden.'),
    'read_error':          (1027, 'Datei kann nicht gelesen werden.'),
    'invite_bot':          (1028, 'Bot einladen'),
    'back':                (1029, 'Zurück'),
    'avatar_none':         (1030, 'Kein Avatar'),

    # ── Navigation Tabs ───────────────────────────────────────
    'tab_main':            (1117, 'Start'),
    'tab_commands':        (1118, 'Befehle'),
    'tab_variables':       (1119, 'Variablen'),
    'tab_settings':        (1120, 'Einstellungen'),
    'tab_wiki':            (1121, 'Wiki'),

    # ── Settings ──────────────────────────────────────────────
    'general_section':     (1031, 'Allgemein'),
    'design_section':      (1032, 'Design'),
    'info_section':        (1033, 'Informationen'),
    'name_project':        (1034, 'Projektname'),
    'token_field':         (1035, 'Bot-Token'),
    'bot_name_hint':       (1036, 'Bot-Name'),
    'bot_token_hint':      (1037, 'Bot-Token'),
    'save':                (1038, 'Speichern'),
    'language':            (1039, 'Sprache'),
    'wiki':                (1040, 'Wiki'),
    'link':                (1041, '(Link)'),
    'restart_notice':      (1042, 'Wird neu gestartet...'),
    'search_lang':         (1043, 'Sprache suchen...'),
    'select_language':     (1044, 'Sprache auswählen'),
    'selfbot_token_blocked': (1045, 'Benutzer-/Selfbot-Token sind aus Sicherheitsgründen strikt untersagt.'),
    'invalid_bot_token':   (1046, 'Ungültiger Bot-Token. Bitte gib einen offiziellen Discord-Bot-Token ein.'),

    # ── Export Data ───────────────────────────────────────────
    'export_section':      (1047, 'Daten exportieren'),
    'export_desc':         (1048, 'Befehle und Variablen als ZIP-Datei exportieren'),
    'export_zip':          (1049, 'ZIP exportieren'),
    'no_bot_selected':     (1050, 'Kein Bot ausgewählt!'),
    'folders_not_found':   (1051, 'Ordner nicht gefunden!'),
    'export_failed':       (1052, 'Export fehlgeschlagen!'),
    'export_success':      (1053, 'Erfolgreich exportiert!'),

    # ── Danger Zone / Delete ──────────────────────────────────
    'danger_zone':         (1054, 'Gefahrenzone'),
    'delete_bot_perm':     (1055, 'Diesen Bot dauerhaft löschen'),
    'captcha_enter':       (1056, '3 Ziffern eingeben'),
    'captcha_hint':        (1057, 'Gib die oben angezeigten 3 Ziffern ein'),
    'confirm_delete':      (1058, 'Löschung bestätigen'),
    'captcha_wrong':       (1059, 'Falscher Code — Versuche es erneut'),

    # ── Themes Names ──────────────────────────────────────────
    'system_wh':           (1060, 'System (Hell)'),
    'system_da':           (1061, 'System (Dunkel)'),
    'blue_sky':            (1062, 'Blau - Himmel'),
    'yellow_bile':         (1063, 'Gelb - Gold'),
    'v2_dark':             (1064, 'Dunkelgold'),

    # ── commands_view ─────────────────────────────────────────
    'commands_slash':      (1065, '/ Befehle'),
    'info_command':        (1066, 'Befehlsinformationen'),
    'command_editor':      (1067, 'Befehlseditor'),
    'total_lines':         (1068, 'Zeilen'),
    'total_text':          (1069, 'Zeichen'),
    'fdscript_hint':       (1070, '# FDScript-Code hier eingeben...'),
    'prefix_label':        (1071, 'Präfix'),
    'prefix_hint':         (1072, 'Beispiel: !cmd'),
    'search':              (1073, 'Suche'),
    'commands':            (1074, 'Befehle'),
    'no_cmds_hint':        (1075, 'Keine Befehle gefunden. Klicke auf +, um einen zu erstellen.'),
    'del':                 (1076, 'Löschen'),
    'name_required':       (1077, 'Name ist erforderlich'),
    'delete_q':            (1078, 'Löschen?'),
    'delete_confirm':      (1079, 'Bist du sicher, dass du "{item_name}" löschen möchtest?\nDiese Aktion kann nicht rückgängig gemacht werden.'),
    'dest_event':          (1080, 'Ereignis'),
    'dest_cmd':            (1081, 'Befehl'),
    'commands_label':      (1082, 'Befehlsnamen eingeben'),
    'unsaved_title':       (1083, 'Nicht gespeicherte Änderungen'),
    'unsaved_body':        (1084, 'Es gibt nicht gespeicherte Änderungen. Möchtest du sie vor dem Verlassen speichern?'),
    'discard':             (1085, 'Verwerfen'),
    'loading':             (1086, 'Wird geladen...'),

    # ── wiki_view ─────────────────────────────────────────────
    'search_hint':          (1122, 'Funktion suchen...'),
    'check_updates':        (1123, 'Nach Updates suchen'),
    'checking':             (1124, 'Wird geprüft...'),
    'downloading':          (1125, 'Wiki wird heruntergeladen...'),
    'up_to_date':           (1126, 'Wiki ist aktuell (v{v})'),
    'update_available':     (1127, 'Neues Update verfügbar (v{v})'),
    'update_failed':        (1128, 'Update-Prüfung fehlgeschlagen'),
    'no_cache':             (1129, 'Noch keine lokalen Daten. Drücke "Nach Updates suchen".'),
    'no_results':           (1130, 'Keine Ergebnisse'),
    'function_info':        (1131, 'Funktionsinformationen'),
    'no_details':           (1132, 'Keine Details verfügbar'),
    'open_dashboard':       (1133, 'Dashboard öffnen'),
    'copy_syntax':          (1134, 'Kopieren'),
    'copied':               (1135, 'Kopiert!'),
    'syntax':               (1136, 'Syntax'),
    'parameters':           (1137, 'Parameter'),
    'example':              (1138, 'Beispiel'),
    'notes':                (1139, 'Hinweise'),
    'warnings':             (1140, 'Warnungen'),
    'required':             (1141, 'Erforderlich'),
    'optional':             (1142, 'Optional'),
    'not_used_in_bot':      (1143, 'Diese Funktion wird in den Befehlen dieses Bots nicht verwendet'),

    # ── wiki_view filters ─────────────────────────────────────
    'filter_all':           (1148, 'Alle'),
    'filter_command':       (1149, 'Befehl'),
    'filter_event':         (1150, 'Ereignis'),
    'filter_variable':      (1171, 'Variablen'),
    'filter_discord':       (1172, 'Discord'),
    'filter_time':          (1173, 'Zeit'),
    'filter_other':         (1174, 'Sonstiges'),
    'filter_title':         (1241, 'Kategorien'),
    'filter_tooltip':       (1246, 'Filter'),
    'no_categories':        (1247, 'Noch keine Kategorien'),

    # ── wiki_view callouts ────────────────────────────────────
    'callout_note':         (1144, 'Hinweis'),
    'callout_limit':        (1145, 'Grenze'),
    'callout_important':    (1146, 'Das ist wichtig!'),
    'callout_question':     (1147, 'Was ist das?'),

    # ── variables_view ────────────────────────────────────────
    'variables':            (1028, 'Variablen'),
    'variables_slash':      (1151, 'Variablen /'),
    'scoped_vars':          (1152, 'Werte pro Benutzer'),
    'value_label':          (1153, 'Wert'),
    'var_name_hint':        (1154, 'variablenname'),
    'var_value_hint':       (1155, 'variablenwert'),
    'info_var':             (1156, 'Variableninformationen'),
    'invalid_json':         (1157, 'Ungültiges JSON'),
    'json_must_be_object':  (1158, 'Der oberste Wert muss ein JSON-Objekt sein ({"userID": "value"}).'),
    'no_variables':         (1089, 'Keine Variablen'),
    'enter_variable_name':  (1106, 'Variablennamen eingeben'),

    # ── App Updater ───────────────────────────────────────────
    'app_update_title':           (1159, 'Update verfügbar'),
    'app_update_new_version':     (1160, 'Neue Version'),
    'app_update_current_version': (1161, 'Aktuell'),
    'app_update_no_changelog':    (1162, 'Kein Änderungsprotokoll für dieses Update verfügbar.'),
    'app_update_later':           (1163, 'Später'),
    'app_update_now':             (1164, 'Jetzt aktualisieren'),
    'app_update_downloading':     (1165, 'Wird heruntergeladen'),
    'app_update_done':            (1166, 'Download abgeschlossen ✓'),
    'app_update_failed':          (1167, 'Download fehlgeschlagen'),
    'app_update_open_installer':  (1168, 'Installer öffnen'),
    'app_update_installer_opened':(1169, 'Installer geöffnet. Schließe die Installation ab und öffne die App danach erneut.'),
    'app_update_open_failed':     (1170, 'Installer-Datei konnte nicht geöffnet werden'),

    # ── Status Bot View ───────────────────────────────────────
    'status_bot_section':         (1175, 'Bot-Status'),
    'status_bot_desc':            (1176, 'Konfiguriere die Präsenz und rotierenden Statusmeldungen deines Bots'),
    'open_status_bot':            (1177, 'Status verwalten'),
    'status_bot_title':           (1178, 'Status-Bot'),
    'sv_status_label':            (1179, 'Status'),
    'sv_loop_time_label':         (1180, 'Umlaufzeit'),
    'sv_loop_time_seconds':       (1181, 'Sekunden'),
    'sv_loop_time_hint':          (1182, 'Nur ganze Zahlen, min. 12 Sekunden'),
    'sv_activate_presence':       (1183, 'Bot-Präsenz aktivieren'),
    'sv_status_entries':          (1184, 'Statuseinträge'),
    'sv_add_entry':               (1185, 'Neuen Eintrag hinzufügen'),
    'sv_entry_details_ph':        (1186, 'Statusdetails'),
    'sv_status_online':           (1187, 'Online'),
    'sv_status_idle':             (1188, 'Abwesend'),
    'sv_status_dnd':              (1189, 'Nicht stören'),
    'sv_status_invisible':        (1190, 'Unsichtbar'),
    'sv_create_edit_title':       (1191, 'Statuseintrag erstellen oder bearbeiten'),
    'sv_status_data':             (1192, 'Statusdaten'),
    'sv_prefix_status':           (1193, 'Status-Präfix'),
    'sv_status_field':            (1194, 'Status'),
    'sv_status_details':          (1195, 'Statusdetails'),
    'sv_prefix_hint':             (1196, 'z. B. Spielt'),
    'sv_status_hint':             (1197, 'Kurzer Statustext'),
    'sv_details_hint':            (1198, 'Zusätzliche Details, die unter dem Status angezeigt werden'),
    'sv_preview':                 (1199, 'Vorschau'),
    'sv_name_bot':                (1200, 'Bot-Name'),
    'sv_app_badge':               (1201, 'APP'),
    'sv_save_entry':              (1202, 'Eintrag speichern'),
    'sv_back':                    (1203, 'Zurück'),
    'sv_no_entries':              (1204, 'Noch keine Statuseinträge.'),
    'sv_unit_second':             (1205, 'Sekunde'),
    'sv_unit_minute':             (1206, 'Minute'),
    'sv_unit_hour':               (1207, 'Stunde'),
    'sv_unit_day':                (1208, 'Tag'),
    'sv_loop_time_integer_error': (1209, 'Nur ganze Zahlen — keine Dezimalstellen oder Symbole'),
    'sv_loop_time_min_error':     (1210, 'Die Umlaufzeit darf nicht unter 12 Sekunden liegen'),
    'sv_activity_type':           (1211, 'Aktivitätstyp'),
    'sv_activity_playing':        (1212, 'Spielt'),
    'sv_activity_streaming':      (1213, 'Streamt'),
    'sv_activity_listening':      (1214, 'Hört'),
    'sv_activity_watching':       (1215, 'Schaut'),
    'sv_activity_competing':      (1216, 'Tritt an bei'),
    'sv_stream_url':              (1217, 'Stream-URL'),
    'sv_stream_url_hint':         (1218, 'https://twitch.tv/... oder https://youtube.com/...'),
    'sv_stream_url_required':     (1219, 'Für den Streaming-Status ist eine Stream-URL erforderlich'),
    'sv_stream_url_invalid':      (1220, 'Nur Twitch- oder YouTube-Links sind erlaubt'),
    'sv_help_note_title':         (1229, 'Hinweise'),
    'sv_help_note_body':          (1230, 'Änderungen benötigen einen Moment, um wirksam zu werden. Das Hinzufügen, '
                                      'Bearbeiten oder Löschen eines Status – sowie das Ein- oder Ausschalten '
                                      'der Präsenz – während der Bot läuft, wird nicht sofort übernommen. '
                                      'Der Bot durchläuft zuerst die aktuelle Liste, daher kann es eine Weile '
                                      'dauern, bis deine Änderung sichtbar wird.'),

    # ── Create Bot — Import from backup ────────────────────────────────────
    'import_zip_btn':           (1221, 'Aus Backup wiederherstellen'),
    'import_zip_disabled_hint': (1222, 'Lege zuerst den Bot-Namen und einen gültigen Token fest'),
    'import_zip_selected':      (1223, 'Backup ausgewählt: {file_name}'),
    'import_zip_clear':         (1224, 'Entfernen'),
    'import_zip_invalid':       (1225, 'Das sieht nicht nach einer Bot-Backup-Datei aus'),
    'import_zip_pick_title':    (1226, 'Backup-ZIP auswählen'),
    'import_zip_applied':       (1227, 'Bot erstellt und Backup wiederhergestellt!'),
    'import_zip_failed':        (1228, 'Bot wurde erstellt, aber die Wiederherstellung des Backups ist fehlgeschlagen'),

    # ── General Actions & Feedback ─────────────────────────────────────────
    'edit':                   (1094, 'Bearbeiten'),
    'delete':                 (1095, 'Löschen'),
    'cancel':                 (1100, 'Abbrechen'),
    'reset':                  (1242, 'Zurücksetzen'),
    'close':                  (1243, 'Schließen'),
    'done':                   (1244, 'Fertig'),
    'clear_search':           (1245, 'Suche zurücksetzen'),
    'saved_successfully':     (1231, 'Erfolgreich gespeichert'),

    # ── Mobile Warning ────────────────────────────────────────────────────
    'mobile_warn_title':      (1232, 'Hinweis zum Mobil-Hintergrundbetrieb'),
    'mobile_warn_body':       (1233, 'Der Betrieb von Bots auf mobilen Systemen (nur Android) unterliegt strengen Hintergrundlimits des Betriebssystems.\n\n• Im besten Fall läuft der Bot nur bis zu 6 Stunden im Hintergrund.\n• Du musst die Akku-Optimierung in den Geräteeinstellungen deaktivieren (auf "Uneingeschränkt" setzen).\n• Manche Geräte pausieren den Bot sofort beim Minimieren.\n\nDer Betrieb der Bots auf Hosting/Server/VPS o. Ä. wird noch nicht unterstützt.'),

    # ── Command Editor Syntax Warning ─────────────────────────────────────
    'syntax_warn_banner':     (1234, 'Der Farbmodus ist aktiv. Deaktiviere ihn bei großen Dateien (>2000 Zeichen), um Geräteverzögerungen zu vermeiden.'),
    'syntax_limit_refusal':   (1235, 'Farbmodus kann nicht aktiviert werden: Der Text überschreitet das Limit von 2000 Zeichen, um die Leistung zu schützen.'),
    'syntax_color_label':     (1236, 'Farbe'),

    # ── Total Counts ──────────────────────────────────────────────────────
    'total_bots_count':       (1237, 'Anzahl deiner Bots: {count}'),
    'total_vars_count':       (1238, 'Anzahl der Variablen: {count}'),
    'total_cmds_count':       (1239, 'Anzahl der Befehle: {count}'),
    'total_wiki_count':       (1240, 'Ergebnisse: {count}'),

    # ── Token Verification ────────────────────────────────────────────────
    'verify_token':           (1248, 'Token überprüfen'),
    'verifying':              (1249, 'Wird überprüft...'),
    'token_valid':            (1250, 'Verbindung erfolgreich! Token ist gültig.'),
    'token_invalid':          (1251, 'Ungültiger Token oder Verbindung fehlgeschlagen.'),

    # ── Android Background Notification ────────────────────────────────────
    'fgs_state_working':          (1252, 'Bot läuft | 🟢'),
    'server_status_online':       (1257, 'Server online: {name}'),
    'server_status_stopped':      (1258, 'Server gestoppt'),
    'fgs_limit_reached':          (1259, 'Android-Hintergrundlimit erreicht (6 Stunden). Öffne die App, um den Server neu zu starten.'),
    'fgs_start_failed':           (1260, 'Hintergrunddienst konnte nicht gestartet werden: {error}'),

    # ── Privileged Gateway Intents Warning ────────────────────────────────
    'intents_warning_title':      (1261, 'Privilegierte Intents deaktiviert'),
    'intents_warning_msg':        (1262, 'Warnung: Privilegierte Gateway-Intents (Präsenz, Mitglieder, Nachrichteninhalt) sind im Discord Developer Portal nicht aktiviert. Befehle und Ereignisse funktionieren möglicherweise nicht korrekt.'),
    'open_dev_portal':            (1263, 'Im Portal aktivieren'),

    'syntax_switch_tooltip': (1264, 'Syntaxhervorhebung umschalten'),
    'new_command_file':      (1265, 'Neu.fds'),
    'wiki_events_tooltip':   (1266, 'Wiki: Ereignisse'),
    'new_variable_file':     (1267, 'neu.json'),
    'scoped_json_title':     (1268, '{name} — Benutzerspezifische JSON-Daten'),
}