# -*- coding: utf-8 -*-
# main_app/langs/en.py

ENGLISH_DICT = {
    # ── Main Interface ────────────────────────────────────────
    'main_title':          (1001, 'FDSB'),
    'no_bots_hint':        (1002, 'No bots found. Click "New Bot" to create one.'),
    'new_bot':             (1003, 'New Bot'),
    'discord':             (1004, 'Discord'),
    'github':              (1005, 'GitHub'),

    # ── Create Bot Window ─────────────────────────────────────
    'name_label':          (1006, 'Name'),
    'token_label':         (1007, 'Token'),
    'name_hint':           (1008, 'Enter bot name'),
    'token_hint':          (1009, 'Enter bot token'),
    'make':                (1010, 'Create'),
    'image_label':         (1011, 'Image'),
    'ok':                  (1012, 'OK'),
    'token_required':      (1013, 'Token is required'),
    'name_taken':          (1014, 'Name already taken\nChoose a different name'),
    'token_invalid_format':(1015, 'Invalid token format.'),

    # ── Bot Dashboard ─────────────────────────────────────────
    'state_server':        (1016, 'Server Status'),
    'online':              (1017, 'Online'),
    'offline':             (1018, 'Offline'),
    'start':               (1019, 'Start'),
    'stop':                (1020, 'Stop'),
    'starting':            (1021, 'Connecting...'),
    'stopping':            (1022, 'Stopping...'),
    'servers_count':       (1023, 'Servers'),
    'whats_new':           (1024, 'What\'s New'),
    'no_updates':          (1025, 'No updates available.'),
    'no_file':             (1026, 'Updates file not found.'),
    'read_error':          (1027, 'Unable to read file.'),
    'invite_bot':          (1028, 'Invite Bot'),
    'back':                (1029, 'Back'),
    'avatar_none':         (1030, 'No Avatar'),

    # ── Navigation Tabs ───────────────────────────────────────
    'tab_main':            (1117, 'Main'),
    'tab_commands':        (1118, 'Commands'),
    'tab_variables':       (1119, 'Variables'),
    'tab_settings':        (1120, 'Settings'),
    'tab_wiki':            (1121, 'Wiki'),

    # ── Settings ──────────────────────────────────────────────
    'general_section':     (1031, 'General'),
    'design_section':      (1032, 'Design'),
    'info_section':        (1033, 'Information'),
    'name_project':        (1034, 'Project Name'),
    'token_field':         (1035, 'Bot Token'),
    'bot_name_hint':       (1036, 'Bot Name'),
    'bot_token_hint':      (1037, 'Bot Token'),
    'save':                (1038, 'Save'),
    'language':            (1039, 'Language'),
    'wiki':                (1040, 'Wiki'),
    'link':                (1041, '(Link)'),
    'restart_notice':      (1042, 'Restarting...'),
    'search_lang':         (1043, 'Search language...'),
    'select_language':     (1044, 'Select Language'),
    'selfbot_token_blocked': (1045, 'User/Self-bot tokens are strictly prohibited for safety and security.'),
    'invalid_bot_token':   (1046, 'Invalid bot token. Please enter an official Discord Bot token.'),

    # ── Export Data ───────────────────────────────────────────
    'export_section':      (1047, 'Export Data'),
    'export_desc':         (1048, 'Export commands and variables as a ZIP file'),
    'export_zip':          (1049, 'Export ZIP'),
    'no_bot_selected':     (1050, 'No bot selected!'),
    'folders_not_found':   (1051, 'Folders not found!'),
    'export_failed':       (1052, 'Export failed!'),
    'export_success':      (1053, 'Exported successfully!'),

    # ── Danger Zone / Delete ──────────────────────────────────
    'danger_zone':         (1054, 'Danger Zone'),
    'delete_bot_perm':     (1055, 'Delete this bot permanently'),
    'captcha_enter':       (1056, 'Enter 3 digits'),
    'captcha_hint':        (1057, 'Enter the 3 digits shown above'),
    'confirm_delete':      (1058, 'Confirm Deletion'),
    'captcha_wrong':       (1059, 'Wrong code — Try again'),

    # ── Themes Names ──────────────────────────────────────────
    'system_wh':           (1060, 'System (Light)'),
    'system_da':           (1061, 'System (Dark)'),
    'blue_sky':            (1062, 'Blue - Sky'),
    'yellow_bile':         (1063, 'Yellow - Gold'),
    'v2_dark':             (1064, 'Dark Gold'),

    # ── commands_view ─────────────────────────────────────────
    'commands_slash':      (1065, '/ Commands'),
    'info_command':        (1066, 'Command Info'),
    'command_editor':      (1067, 'Command Editor'),
    'total_lines':         (1068, 'Lines'),
    'total_text':          (1069, 'Characters'),
    'fdscript_hint':       (1070, '# FDScript code here...'),
    'prefix_label':        (1071, 'Prefix'),
    'prefix_hint':         (1072, 'Example: !cmd'),
    'search':              (1073, 'Search'),
    'commands':            (1074, 'Commands'),
    'no_cmds_hint':        (1075, 'No commands found. Click + to create one.'),
    'del':                 (1076, 'Delete'),
    'name_required':       (1077, 'Name is required'),
    'delete_q':            (1078, 'Delete?'),
    'delete_confirm':      (1079, 'Are you sure you want to delete "{item_name}"?\nThis action cannot be undone.'),
    'dest_event':          (1080, 'Event'),
    'dest_cmd':            (1081, 'Command'),
    'commands_label':      (1082, 'Enter command name'),
    'unsaved_title':       (1083, 'Unsaved Changes'),
    'unsaved_body':        (1084, 'There are unsaved changes. Do you want to save them before exiting?'),
    'discard':             (1085, 'Discard'),
    'loading':             (1086, 'Loading...'),

    # ── wiki_view ─────────────────────────────────────────────
    'search_hint':          (1122, 'Search a function...'),
    'check_updates':        (1123, 'Check for updates'),
    'checking':             (1124, 'Checking...'),
    'downloading':          (1125, 'Downloading wiki...'),
    'up_to_date':           (1126, 'Wiki is up to date (v{v})'),
    'update_available':     (1127, 'New update available (v{v})'),
    'update_failed':        (1128, 'Failed to check for updates'),
    'no_cache':             (1129, 'No local data yet. Press "Check for updates".'),
    'no_results':           (1130, 'No results'),
    'function_info':        (1131, 'Function info'),
    'no_details':           (1132, 'No details available'),
    'open_dashboard':       (1133, 'Open dashboard'),
    'copy_syntax':          (1134, 'Copy'),
    'copied':               (1135, 'Copied!'),
    'syntax':               (1136, 'Syntax'),
    'parameters':           (1137, 'Parameters'),
    'example':              (1138, 'Example'),
    'notes':                (1139, 'Notes'),
    'warnings':             (1140, 'Warnings'),
    'required':             (1141, 'Required'),
    'optional':             (1142, 'Optional'),
    'not_used_in_bot':      (1143, "This function is not used in this bot's commands"),

    # ── wiki_view filters ─────────────────────────────────────
    'filter_all':           (1148, 'All'),
    'filter_command':       (1149, 'Command'),
    'filter_event':         (1150, 'Event'),
    'filter_variable':      (1171, 'Variables'),
    'filter_discord':       (1172, 'Discord'),
    'filter_time':          (1173, 'Time'),
    'filter_other':         (1174, 'Other'),
    'filter_title':         (1241, 'Categories'),
    'filter_tooltip':       (1246, 'Filter'),
    'no_categories':        (1247, 'No categories yet'),

    # ── wiki_view callouts ────────────────────────────────────
    'callout_note':         (1144, 'Note'),
    'callout_limit':        (1145, 'Limit'),
    'callout_important':    (1146, "It's important!"),
    'callout_question':     (1147, 'What is this?'),

    # ── variables_view ────────────────────────────────────────
    'variables':            (1028, 'Variables'),
    'variables_slash':      (1151, "Variable's /"),
    'scoped_vars':          (1152, 'Per-user values'),
    'value_label':          (1153, 'Value'),
    'var_name_hint':        (1154, 'variable_name'),
    'var_value_hint':       (1155, 'variable_value'),
    'info_var':             (1156, 'Variable Info'),
    'invalid_json':         (1157, 'Invalid JSON'),
    'json_must_be_object':  (1158, 'Top level value must be a JSON object ({"userID": "value"}).'),
    'no_variables':         (1089, 'No variables'),
    'enter_variable_name':  (1106, 'Enter variable name'),

    # ── App Updater ───────────────────────────────────────────
    'app_update_title':           (1159, 'Update Available'),
    'app_update_new_version':     (1160, 'New Version'),
    'app_update_current_version': (1161, 'Current'),
    'app_update_no_changelog':    (1162, 'No changelog available for this update.'),
    'app_update_later':           (1163, 'Later'),
    'app_update_now':             (1164, 'Update Now'),
    'app_update_downloading':     (1165, 'Downloading'),
    'app_update_done':            (1166, 'Download complete ✓'),
    'app_update_failed':          (1167, 'Download failed'),
    'app_update_open_installer':  (1168, 'Open Installer'),
    'app_update_installer_opened':(1169, 'Installer opened. Finish installing, then reopen the app.'),
    'app_update_open_failed':     (1170, 'Could not open the installer file'),

    # ── Status Bot View ───────────────────────────────────────
    'status_bot_section':         (1175, 'Bot Status'),
    'status_bot_desc':            (1176, "Configure your bot's presence and rotating status messages"),
    'open_status_bot':            (1177, 'Manage Status'),
    'status_bot_title':           (1178, 'Status Bot'),
    'sv_status_label':            (1179, 'Status'),
    'sv_loop_time_label':         (1180, 'Loop Time'),
    'sv_loop_time_seconds':       (1181, 'Seconds'),
    'sv_loop_time_hint':          (1182, 'Whole number only, min. 12 seconds'),
    'sv_activate_presence':       (1183, 'Activating bot presence'),
    'sv_status_entries':          (1184, 'Status entries'),
    'sv_add_entry':               (1185, 'Add a new entry'),
    'sv_entry_details_ph':        (1186, 'Status details'),
    'sv_status_online':           (1187, 'Online'),
    'sv_status_idle':             (1188, 'Idle'),
    'sv_status_dnd':              (1189, 'Do Not Disturb'),
    'sv_status_invisible':        (1190, 'Invisible'),
    'sv_create_edit_title':       (1191, 'Create or edit status entry'),
    'sv_status_data':             (1192, 'Status Data'),
    'sv_prefix_status':           (1193, 'Prefix status'),
    'sv_status_field':            (1194, 'Status'),
    'sv_status_details':          (1195, 'Status of Details'),
    'sv_prefix_hint':             (1196, 'e.g. Playing'),
    'sv_status_hint':             (1197, 'Short status text'),
    'sv_details_hint':            (1198, 'Extra details shown under the status'),
    'sv_preview':                 (1199, 'Preview'),
    'sv_name_bot':                (1200, 'Name Bot'),
    'sv_app_badge':               (1201, 'APP'),
    'sv_save_entry':              (1202, 'Save Entry'),
    'sv_back':                    (1203, 'Back'),
    'sv_no_entries':              (1204, 'No status entries yet.'),
    'sv_unit_second':             (1205, 'Second'),
    'sv_unit_minute':             (1206, 'Minute'),
    'sv_unit_hour':               (1207, 'Hour'),
    'sv_unit_day':                (1208, 'Day'),
    'sv_loop_time_integer_error': (1209, 'Whole numbers only — no decimals or symbols'),
    'sv_loop_time_min_error':     (1210, 'Loop time cannot be less than 12 seconds'),
    'sv_activity_type':           (1211, 'Activity Type'),
    'sv_activity_playing':        (1212, 'Playing'),
    'sv_activity_streaming':      (1213, 'Streaming'),
    'sv_activity_listening':      (1214, 'Listening to'),
    'sv_activity_watching':       (1215, 'Watching'),
    'sv_activity_competing':      (1216, 'Competing in'),
    'sv_stream_url':              (1217, 'Stream URL'),
    'sv_stream_url_hint':         (1218, 'https://twitch.tv/... or https://youtube.com/...'),
    'sv_stream_url_required':     (1219, 'A stream URL is required for the Streaming status'),
    'sv_stream_url_invalid':      (1220, 'Only Twitch or YouTube links are allowed'),
    'sv_help_note_title':         (1229, 'Notes'),
    'sv_help_note_body':          (1230, "Changes take a moment to go live. Adding, editing, or deleting a "
                                      "status — and turning presence on or off — while the bot is "
                                      "running won't apply instantly. The bot finishes rotating through "
                                      "the current list first, so it may take a short while before your "
                                      "update shows up."),

    # ── Create Bot — Import from backup ────────────────────────────────────
    'import_zip_btn':           (1221, 'Restore from Backup'),
    'import_zip_disabled_hint': (1222, 'Set the bot name and a valid token first'),
    'import_zip_selected':      (1223, 'Backup selected: {file_name}'),
    'import_zip_clear':         (1224, 'Remove'),
    'import_zip_invalid':       (1225, "This doesn't look like a bot backup file"),
    'import_zip_pick_title':    (1226, 'Choose a backup ZIP'),
    'import_zip_applied':       (1227, 'Bot created and backup restored!'),
    'import_zip_failed':        (1228, 'Bot was created, but restoring the backup failed'),

    # ── General Actions & Feedback ─────────────────────────────────────────
    'edit':                   (1094, 'Edit'),
    'delete':                 (1095, 'Delete'),
    'cancel':                 (1100, 'Cancel'),
    'reset':                  (1242, 'Reset'),
    'close':                  (1243, 'Close'),
    'done':                   (1244, 'Done'),
    'clear_search':           (1245, 'Clear search'),
    'saved_successfully':     (1231, 'Saved successfully'),

    # ── Mobile Warning ────────────────────────────────────────────────────
    'mobile_warn_title':      (1232, 'Mobile Background Notice'),
    'mobile_warn_body':       (1233, 'Running bots on mobile systems (only Android) is subject to strict OS background limits.\n\n• In best-case scenarios, the bot may run in the background for up to 6 hours only.\n• You must disable Battery Optimization (set to "Unrestricted") in your device settings.\n• Some devices may suspend the bot immediately when minimized.\n\nRegarding running the bots on hosting/server/vps or something like that, it is not supported yet.'),
    
    # ── Command Editor Syntax Warning ─────────────────────────────────────
    'syntax_warn_banner':     (1234, 'Color mode is active. For large files (>2000 chars), switch off color mode to prevent device lag.'),
    'syntax_limit_refusal':   (1235, 'Cannot enable color mode: Text exceeds the 2000 characters limit to protect performance.'),
    'syntax_color_label':     (1236, 'Color'),
    
    # ── Total Counts ──────────────────────────────────────────────────────
    'total_bots_count':       (1237, 'Total bots you own: {count}'),
    'total_vars_count':       (1238, 'Total variables: {count}'),
    'total_cmds_count':       (1239, 'Total commands: {count}'),
    'total_wiki_count':       (1240, 'Results: {count}'),

    # ── Token Verification ────────────────────────────────────────────────
    'verify_token':           (1248, 'Verify Token'),
    'verifying':              (1249, 'Verifying...'),
    'token_valid':            (1250, 'Connection successful! Token is valid.'),
    'token_invalid':          (1251, 'Invalid Token or Connection failed.'),
    
    # ── Android Background Notification ────────────────────────────────────
    'fgs_state_working':          (1252, 'Bot is running | 🟢'),
    'server_status_online':       (1257, 'Server online: {name}'),
    'server_status_stopped':      (1258, 'Server stopped'),
    'fgs_limit_reached':          (1259, 'Android background limit reached (6 hours). Open the app to restart the server.'),
    'fgs_start_failed':           (1260, 'Failed to start background service: {error}'),

    # ── Privileged Gateway Intents Warning ────────────────────────────────
    'intents_warning_title':      (1261, 'Privileged Intents Disabled'),
    'intents_warning_msg':        (1262, 'Warning: Privileged Gateway Intents (Presence, Members, Message Content) are not enabled in Discord Developer Portal. Commands and events may not work correctly.'),
    'open_dev_portal':            (1263, 'Enable in Portal'),

    'syntax_switch_tooltip': (1264, 'Toggle syntax highlighting'),
    'new_command_file':      (1265, 'New.fds'),
    'wiki_events_tooltip':   (1266, 'Wiki: Events'),
    'new_variable_file':     (1267, 'new.json'),
    'scoped_json_title':     (1268, '{name} — Scoped JSON Data'),
}