# -*- coding: utf-8 -*-
# main_app/langs/fr.py

FRENCH_DICT = {
    # ── Main Interface ────────────────────────────────────────
    'main_title':          (1001, 'FDSB'),
    'no_bots_hint':        (1002, 'Aucun bot trouvé. Cliquez sur « Nouveau bot » pour en créer un.'),
    'new_bot':             (1003, 'Nouveau bot'),
    'discord':             (1004, 'Discord'),
    'github':              (1005, 'GitHub'),

    # ── Create Bot Window ─────────────────────────────────────
    'name_label':          (1006, 'Nom'),
    'token_label':         (1007, 'Jeton'),
    'name_hint':           (1008, 'Entrez le nom du bot'),
    'token_hint':          (1009, 'Entrez le jeton du bot'),
    'make':                (1010, 'Créer'),
    'image_label':         (1011, 'Image'),
    'ok':                  (1012, 'OK'),
    'token_required':      (1013, 'Le jeton est requis'),
    'name_taken':          (1014, 'Ce nom est déjà pris\nChoisissez un autre nom'),
    'token_invalid_format':(1015, 'Format de jeton invalide.'),

    # ── Bot Dashboard ─────────────────────────────────────────
    'state_server':        (1016, 'État du serveur'),
    'online':              (1017, 'En ligne'),
    'offline':             (1018, 'Hors ligne'),
    'start':               (1019, 'Démarrer'),
    'stop':                (1020, 'Arrêter'),
    'starting':            (1021, 'Connexion en cours...'),
    'stopping':            (1022, 'Arrêt en cours...'),
    'servers_count':       (1023, 'Serveurs'),
    'whats_new':           (1024, 'Nouveautés'),
    'no_updates':          (1025, 'Aucune mise à jour disponible.'),
    'no_file':             (1026, 'Fichier de mise à jour introuvable.'),
    'read_error':          (1027, 'Impossible de lire le fichier.'),
    'invite_bot':          (1028, 'Inviter le bot'),
    'back':                (1029, 'Retour'),
    'avatar_none':         (1030, 'Aucun avatar'),

    # ── Navigation Tabs ───────────────────────────────────────
    'tab_main':            (1117, 'Accueil'),
    'tab_commands':        (1118, 'Commandes'),
    'tab_variables':       (1119, 'Variables'),
    'tab_settings':        (1120, 'Paramètres'),
    'tab_wiki':            (1121, 'Wiki'),

    # ── Settings ──────────────────────────────────────────────
    'general_section':     (1031, 'Général'),
    'design_section':      (1032, 'Apparence'),
    'info_section':        (1033, 'Informations'),
    'name_project':        (1034, 'Nom du projet'),
    'token_field':         (1035, 'Jeton du bot'),
    'bot_name_hint':       (1036, 'Nom du bot'),
    'bot_token_hint':      (1037, 'Jeton du bot'),
    'save':                (1038, 'Enregistrer'),
    'language':            (1039, 'Langue'),
    'wiki':                (1040, 'Wiki'),
    'link':                (1041, '(Lien)'),
    'restart_notice':      (1042, 'Redémarrage en cours...'),
    'search_lang':         (1043, 'Rechercher une langue...'),
    'select_language':     (1044, 'Sélectionner la langue'),
    'selfbot_token_blocked': (1045, 'Les jetons utilisateur/self-bot sont strictement interdits pour des raisons de sécurité.'),
    'invalid_bot_token':   (1046, 'Jeton de bot invalide. Veuillez saisir un jeton de bot Discord officiel.'),

    # ── Export Data ───────────────────────────────────────────
    'export_section':      (1047, 'Exporter les données'),
    'export_desc':         (1048, 'Exporter les commandes et les variables sous forme de fichier ZIP'),
    'export_zip':          (1049, 'Exporter en ZIP'),
    'no_bot_selected':     (1050, 'Aucun bot sélectionné !'),
    'folders_not_found':   (1051, 'Dossiers introuvables !'),
    'export_failed':       (1052, 'Échec de l\'exportation !'),
    'export_success':      (1053, 'Exportation réussie !'),

    # ── Danger Zone / Delete ──────────────────────────────────
    'danger_zone':         (1054, 'Zone de danger'),
    'delete_bot_perm':     (1055, 'Supprimer définitivement ce bot'),
    'captcha_enter':       (1056, 'Entrez les 3 chiffres'),
    'captcha_hint':        (1057, 'Entrez les 3 chiffres affichés ci-dessus'),
    'confirm_delete':      (1058, 'Confirmer la suppression'),
    'captcha_wrong':       (1059, 'Code incorrect — Réessayez'),

    # ── Themes Names ──────────────────────────────────────────
    'system_wh':           (1060, 'Système (Clair)'),
    'system_da':           (1061, 'Système (Sombre)'),
    'blue_sky':            (1062, 'Bleu - Ciel'),
    'yellow_bile':         (1063, 'Jaune - Or'),
    'v2_dark':             (1064, 'Or sombre'),

    # ── commands_view ─────────────────────────────────────────
    'commands_slash':      (1065, 'Commandes /'),
    'info_command':        (1066, 'Informations sur la commande'),
    'command_editor':      (1067, 'Éditeur de commandes'),
    'total_lines':         (1068, 'Lignes'),
    'total_text':          (1069, 'Caractères'),
    'fdscript_hint':       (1070, '# Code FDScript ici...'),
    'prefix_label':        (1071, 'Préfixe'),
    'prefix_hint':         (1072, 'Exemple : !cmd'),
    'search':              (1073, 'Rechercher'),
    'commands':            (1074, 'Commandes'),
    'no_cmds_hint':        (1075, 'Aucune commande trouvée. Cliquez sur + pour en créer une.'),
    'del':                 (1076, 'Supprimer'),
    'name_required':       (1077, 'Le nom est requis'),
    'delete_q':            (1078, 'Supprimer ?'),
    'delete_confirm':      (1079, 'Êtes-vous sûr de vouloir supprimer « {item_name} » ?\nCette action est irréversible.'),
    'dest_event':          (1080, 'Événement'),
    'dest_cmd':            (1081, 'Commande'),
    'commands_label':      (1082, 'Entrez le nom de la commande'),
    'unsaved_title':       (1083, 'Modifications non enregistrées'),
    'unsaved_body':        (1084, 'Des modifications n\'ont pas été enregistrées. Voulez-vous les enregistrer avant de quitter ?'),
    'discard':             (1085, 'Ignorer'),
    'loading':             (1086, 'Chargement...'),

    # ── wiki_view ─────────────────────────────────────────────
    'search_hint':          (1122, 'Rechercher une fonction...'),
    'check_updates':        (1123, 'Vérifier les mises à jour'),
    'checking':             (1124, 'Vérification en cours...'),
    'downloading':          (1125, 'Téléchargement du wiki...'),
    'up_to_date':           (1126, 'Le wiki est à jour (v{v})'),
    'update_available':     (1127, 'Nouvelle mise à jour disponible (v{v})'),
    'update_failed':        (1128, 'Échec de la vérification des mises à jour'),
    'no_cache':             (1129, 'Aucune donnée locale pour le moment. Appuyez sur « Vérifier les mises à jour ».'),
    'no_results':           (1130, 'Aucun résultat'),
    'function_info':        (1131, 'Informations sur la fonction'),
    'no_details':           (1132, 'Aucun détail disponible'),
    'open_dashboard':       (1133, 'Ouvrir le tableau de bord'),
    'copy_syntax':          (1134, 'Copier'),
    'copied':               (1135, 'Copié !'),
    'syntax':               (1136, 'Syntaxe'),
    'parameters':           (1137, 'Paramètres'),
    'example':              (1138, 'Exemple'),
    'notes':                (1139, 'Notes'),
    'warnings':             (1140, 'Avertissements'),
    'required':             (1141, 'Requis'),
    'optional':             (1142, 'Optionnel'),
    'not_used_in_bot':      (1143, 'Cette fonction n\'est pas utilisée dans les commandes de ce bot'),

    # ── wiki_view filters ─────────────────────────────────────
    'filter_all':           (1148, 'Tout'),
    'filter_command':       (1149, 'Commande'),
    'filter_event':         (1150, 'Événement'),
    'filter_variable':      (1171, 'Variables'),
    'filter_discord':       (1172, 'Discord'),
    'filter_time':          (1173, 'Temps'),
    'filter_other':         (1174, 'Autre'),
    'filter_title':         (1241, 'Catégories'),
    'filter_tooltip':       (1246, 'Filtrer'),
    'no_categories':        (1247, 'Aucune catégorie pour le moment'),

    # ── wiki_view callouts ────────────────────────────────────
    'callout_note':         (1144, 'Remarque'),
    'callout_limit':        (1145, 'Limite'),
    'callout_important':    (1146, 'C\'est important !'),
    'callout_question':     (1147, 'Qu\'est-ce que c\'est ?'),

    # ── variables_view ────────────────────────────────────────
    'variables':            (1028, 'Variables'),
    'variables_slash':      (1151, 'Variables /'),
    'scoped_vars':          (1152, 'Valeurs par utilisateur'),
    'value_label':          (1153, 'Valeur'),
    'var_name_hint':        (1154, 'nom_variable'),
    'var_value_hint':       (1155, 'valeur_variable'),
    'info_var':             (1156, 'Informations sur la variable'),
    'invalid_json':         (1157, 'JSON invalide'),
    'json_must_be_object':  (1158, 'La valeur de premier niveau doit être un objet JSON ({"userID": "value"}).'),
    'no_variables':         (1089, 'Aucune variable'),
    'enter_variable_name':  (1106, 'Entrez le nom de la variable'),

    # ── App Updater ───────────────────────────────────────────
    'app_update_title':           (1159, 'Mise à jour disponible'),
    'app_update_new_version':     (1160, 'Nouvelle version'),
    'app_update_current_version': (1161, 'Actuelle'),
    'app_update_no_changelog':    (1162, 'Aucun journal des modifications disponible pour cette mise à jour.'),
    'app_update_later':           (1163, 'Plus tard'),
    'app_update_now':             (1164, 'Mettre à jour maintenant'),
    'app_update_downloading':     (1165, 'Téléchargement'),
    'app_update_done':            (1166, 'Téléchargement terminé ✓'),
    'app_update_failed':          (1167, 'Échec du téléchargement'),
    'app_update_open_installer':  (1168, 'Ouvrir l\'installateur'),
    'app_update_installer_opened':(1169, 'Installateur ouvert. Terminez l\'installation, puis rouvrez l\'application.'),
    'app_update_open_failed':     (1170, 'Impossible d\'ouvrir le fichier d\'installation'),

    # ── Status Bot View ───────────────────────────────────────
    'status_bot_section':         (1175, 'Statut du bot'),
    'status_bot_desc':            (1176, 'Configurez la présence de votre bot et ses messages de statut rotatifs'),
    'open_status_bot':            (1177, 'Gérer le statut'),
    'status_bot_title':           (1178, 'Bot de statut'),
    'sv_status_label':            (1179, 'Statut'),
    'sv_loop_time_label':         (1180, 'Durée de la boucle'),
    'sv_loop_time_seconds':       (1181, 'Secondes'),
    'sv_loop_time_hint':          (1182, 'Nombre entier uniquement, min. 12 secondes'),
    'sv_activate_presence':       (1183, 'Activer la présence du bot'),
    'sv_status_entries':          (1184, 'Entrées de statut'),
    'sv_add_entry':               (1185, 'Ajouter une nouvelle entrée'),
    'sv_entry_details_ph':        (1186, 'Détails du statut'),
    'sv_status_online':           (1187, 'En ligne'),
    'sv_status_idle':             (1188, 'Absent'),
    'sv_status_dnd':              (1189, 'Ne pas déranger'),
    'sv_status_invisible':        (1190, 'Invisible'),
    'sv_create_edit_title':       (1191, 'Créer ou modifier une entrée de statut'),
    'sv_status_data':             (1192, 'Données de statut'),
    'sv_prefix_status':           (1193, 'Préfixe du statut'),
    'sv_status_field':            (1194, 'Statut'),
    'sv_status_details':          (1195, 'Détails du statut'),
    'sv_prefix_hint':             (1196, 'ex. : Joue à'),
    'sv_status_hint':             (1197, 'Texte de statut court'),
    'sv_details_hint':            (1198, 'Détails supplémentaires affichés sous le statut'),
    'sv_preview':                 (1199, 'Aperçu'),
    'sv_name_bot':                (1200, 'Nom du bot'),
    'sv_app_badge':               (1201, 'APP'),
    'sv_save_entry':              (1202, 'Enregistrer l\'entrée'),
    'sv_back':                    (1203, 'Retour'),
    'sv_no_entries':              (1204, 'Aucune entrée de statut pour le moment.'),
    'sv_unit_second':             (1205, 'Seconde'),
    'sv_unit_minute':             (1206, 'Minute'),
    'sv_unit_hour':               (1207, 'Heure'),
    'sv_unit_day':                (1208, 'Jour'),
    'sv_loop_time_integer_error': (1209, 'Nombres entiers uniquement — aucune décimale ni symbole'),
    'sv_loop_time_min_error':     (1210, 'La durée de la boucle ne peut pas être inférieure à 12 secondes'),
    'sv_activity_type':           (1211, 'Type d\'activité'),
    'sv_activity_playing':        (1212, 'Joue à'),
    'sv_activity_streaming':      (1213, 'Diffuse en direct'),
    'sv_activity_listening':      (1214, 'Écoute'),
    'sv_activity_watching':       (1215, 'Regarde'),
    'sv_activity_competing':      (1216, 'Participe à'),
    'sv_stream_url':              (1217, 'URL du flux'),
    'sv_stream_url_hint':         (1218, 'https://twitch.tv/... ou https://youtube.com/...'),
    'sv_stream_url_required':     (1219, 'Une URL de flux est requise pour le statut Diffusion en direct'),
    'sv_stream_url_invalid':      (1220, 'Seuls les liens Twitch ou YouTube sont autorisés'),
    'sv_help_note_title':         (1229, 'Remarques'),
    'sv_help_note_body':          (1230, 'Les modifications prennent un moment avant d\'être appliquées. Ajouter, '
                                      'modifier ou supprimer un statut — et activer ou désactiver la présence — '
                                      'pendant que le bot fonctionne ne s\'applique pas instantanément. Le bot '
                                      'termine d\'abord la liste en cours, il peut donc s\'écouler un moment avant '
                                      'que votre modification apparaisse.'),

    # ── Create Bot — Import from backup ────────────────────────────────────
    'import_zip_btn':           (1221, 'Restaurer depuis une sauvegarde'),
    'import_zip_disabled_hint': (1222, 'Définissez d\'abord le nom du bot et un jeton valide'),
    'import_zip_selected':      (1223, 'Sauvegarde sélectionnée : {file_name}'),
    'import_zip_clear':         (1224, 'Retirer'),
    'import_zip_invalid':       (1225, 'Cela ne ressemble pas à un fichier de sauvegarde de bot'),
    'import_zip_pick_title':    (1226, 'Choisir un fichier ZIP de sauvegarde'),
    'import_zip_applied':       (1227, 'Bot créé et sauvegarde restaurée !'),
    'import_zip_failed':        (1228, 'Le bot a été créé, mais la restauration de la sauvegarde a échoué'),

    # ── General Actions & Feedback ─────────────────────────────────────────
    'edit':                   (1094, 'Modifier'),
    'delete':                 (1095, 'Supprimer'),
    'cancel':                 (1100, 'Annuler'),
    'reset':                  (1242, 'Réinitialiser'),
    'close':                  (1243, 'Fermer'),
    'done':                   (1244, 'Terminé'),
    'clear_search':           (1245, 'Effacer la recherche'),
    'saved_successfully':     (1231, 'Enregistré avec succès'),

    # ── Mobile Warning ────────────────────────────────────────────────────
    'mobile_warn_title':      (1232, 'Avis sur l\'exécution en arrière-plan mobile'),
    'mobile_warn_body':       (1233, 'L\'exécution de bots sur des systèmes mobiles (Android uniquement) est soumise à des limites strictes d\'arrière-plan imposées par le système d\'exploitation.\n\n• Dans le meilleur des cas, le bot ne peut fonctionner en arrière-plan que pendant 6 heures maximum.\n• Vous devez désactiver l\'optimisation de la batterie (la régler sur « Illimité ») dans les paramètres de votre appareil.\n• Certains appareils peuvent suspendre le bot immédiatement lors de sa mise en arrière-plan.\n\nQuant à l\'exécution des bots sur un hébergement/serveur/VPS ou similaire, ce n\'est pas encore pris en charge.'),

    # ── Command Editor Syntax Warning ─────────────────────────────────────
    'syntax_warn_banner':     (1234, 'Le mode couleur est actif. Pour les fichiers volumineux (>2000 caractères), désactivez le mode couleur pour éviter les ralentissements de l\'appareil.'),
    'syntax_limit_refusal':   (1235, 'Impossible d\'activer le mode couleur : le texte dépasse la limite de 2000 caractères pour préserver les performances.'),
    'syntax_color_label':     (1236, 'Couleur'),

    # ── Total Counts ──────────────────────────────────────────────────────
    'total_bots_count':       (1237, 'Nombre total de bots que vous possédez : {count}'),
    'total_vars_count':       (1238, 'Nombre total de variables : {count}'),
    'total_cmds_count':       (1239, 'Nombre total de commandes : {count}'),
    'total_wiki_count':       (1240, 'Résultats : {count}'),

    # ── Token Verification ────────────────────────────────────────────────
    'verify_token':           (1248, 'Vérifier le jeton'),
    'verifying':              (1249, 'Vérification en cours...'),
    'token_valid':            (1250, 'Connexion réussie ! Le jeton est valide.'),
    'token_invalid':          (1251, 'Jeton invalide ou échec de la connexion.'),

    # ── Android Background Notification ────────────────────────────────────
    'fgs_state_working':          (1252, 'Le bot est en cours d\'exécution | 🟢'),
    'server_status_online':       (1257, 'Serveur en ligne : {name}'),
    'server_status_stopped':      (1258, 'Serveur arrêté'),
    'fgs_limit_reached':          (1259, 'Limite d\'arrière-plan Android atteinte (6 heures). Ouvrez l\'application pour redémarrer le serveur.'),
    'fgs_start_failed':           (1260, 'Échec du démarrage du service en arrière-plan : {error}'),

    # ── Privileged Gateway Intents Warning ────────────────────────────────
    'intents_warning_title':      (1261, 'Intentions privilégiées désactivées'),
    'intents_warning_msg':        (1262, 'Avertissement : les intentions privilégiées de la passerelle (Présence, Membres, Contenu des messages) ne sont pas activées dans le portail développeur Discord. Les commandes et les événements pourraient ne pas fonctionner correctement.'),
    'open_dev_portal':            (1263, 'Activer dans le portail'),

    'syntax_switch_tooltip': (1264, 'Basculer la coloration syntaxique'),
    'new_command_file':      (1265, 'Nouveau.fds'),
    'wiki_events_tooltip':   (1266, 'Wiki : Événements'),
    'new_variable_file':     (1267, 'nouveau.json'),
    'scoped_json_title':     (1268, '{name} — Données JSON par utilisateur'),
}