# -*- coding: utf-8 -*-
# main_app/langs/pl.py

POLISH_DICT = {
    # ── Main Interface ────────────────────────────────────────
    'main_title':          (1001, 'FDSB'),
    'no_bots_hint':        (1002, 'Nie znaleziono botów. Kliknij "Nowy bot", aby go utworzyć.'),
    'new_bot':             (1003, 'Nowy bot'),
    'discord':             (1004, 'Discord'),
    'github':              (1005, 'GitHub'),

    # ── Create Bot Window ─────────────────────────────────────
    'name_label':          (1006, 'Nazwa'),
    'token_label':         (1007, 'Token'),
    'name_hint':           (1008, 'Wpisz nazwę bota'),
    'token_hint':          (1009, 'Wpisz token bota'),
    'make':                (1010, 'Utwórz'),
    'image_label':         (1011, 'Obraz'),
    'ok':                  (1012, 'OK'),
    'token_required':      (1013, 'Token jest wymagany'),
    'name_taken':          (1014, 'Ta nazwa jest już zajęta\nWybierz inną nazwę'),
    'token_invalid_format':(1015, 'Nieprawidłowy format tokenu.'),

    # ── Bot Dashboard ─────────────────────────────────────────
    'state_server':        (1016, 'Status serwera'),
    'online':              (1017, 'Online'),
    'offline':             (1018, 'Offline'),
    'start':               (1019, 'Uruchom'),
    'stop':                (1020, 'Zatrzymaj'),
    'starting':            (1021, 'Łączenie...'),
    'stopping':            (1022, 'Zatrzymywanie...'),
    'servers_count':       (1023, 'Serwery'),
    'whats_new':           (1024, 'Co nowego'),
    'no_updates':          (1025, 'Brak dostępnych aktualizacji.'),
    'no_file':             (1026, 'Nie znaleziono pliku aktualizacji.'),
    'read_error':          (1027, 'Nie można odczytać pliku.'),
    'invite_bot':          (1028, 'Zaproś bota'),
    'back':                (1029, 'Wstecz'),
    'avatar_none':         (1030, 'Brak awatara'),

    # ── Navigation Tabs ───────────────────────────────────────
    'tab_main':            (1117, 'Główna'),
    'tab_commands':        (1118, 'Komendy'),
    'tab_variables':       (1119, 'Zmienne'),
    'tab_settings':        (1120, 'Ustawienia'),
    'tab_wiki':            (1121, 'Wiki'),

    # ── Settings ──────────────────────────────────────────────
    'general_section':     (1031, 'Ogólne'),
    'design_section':      (1032, 'Wygląd'),
    'info_section':        (1033, 'Informacje'),
    'name_project':        (1034, 'Nazwa projektu'),
    'token_field':         (1035, 'Token bota'),
    'bot_name_hint':       (1036, 'Nazwa bota'),
    'bot_token_hint':      (1037, 'Token bota'),
    'save':                (1038, 'Zapisz'),
    'language':            (1039, 'Język'),
    'wiki':                (1040, 'Wiki'),
    'link':                (1041, '(Link)'),
    'restart_notice':      (1042, 'Restartowanie...'),
    'search_lang':         (1043, 'Szukaj języka...'),
    'select_language':     (1044, 'Wybierz język'),
    'selfbot_token_blocked': (1045, 'Tokeny użytkowników/self-botów są surowo zabronione ze względów bezpieczeństwa.'),
    'invalid_bot_token':   (1046, 'Nieprawidłowy token bota. Wprowadź oficjalny token bota Discord.'),

    # ── Export Data ───────────────────────────────────────────
    'export_section':      (1047, 'Eksport danych'),
    'export_desc':         (1048, 'Eksportuj komendy i zmienne jako plik ZIP'),
    'export_zip':          (1049, 'Eksportuj ZIP'),
    'no_bot_selected':     (1050, 'Nie wybrano bota!'),
    'folders_not_found':   (1051, 'Nie znaleziono folderów!'),
    'export_failed':       (1052, 'Eksport nie powiódł się!'),
    'export_success':      (1053, 'Eksport zakończony pomyślnie!'),

    # ── Danger Zone / Delete ──────────────────────────────────
    'danger_zone':         (1054, 'Strefa zagrożenia'),
    'delete_bot_perm':     (1055, 'Usuń tego bota na stałe'),
    'captcha_enter':       (1056, 'Wpisz 3 cyfry'),
    'captcha_hint':        (1057, 'Wpisz 3 cyfry pokazane powyżej'),
    'confirm_delete':      (1058, 'Potwierdź usunięcie'),
    'captcha_wrong':       (1059, 'Nieprawidłowy kod — Spróbuj ponownie'),

    # ── Themes Names ──────────────────────────────────────────
    'system_wh':           (1060, 'Systemowy (Jasny)'),
    'system_da':           (1061, 'Systemowy (Ciemny)'),
    'blue_sky':            (1062, 'Niebieski - Niebo'),
    'yellow_bile':         (1063, 'Żółty - Złoty'),
    'v2_dark':             (1064, 'Ciemne złoto'),

    # ── commands_view ─────────────────────────────────────────
    'commands_slash':      (1065, 'Komendy /'),
    'info_command':        (1066, 'Informacje o komendzie'),
    'command_editor':      (1067, 'Edytor komend'),
    'total_lines':         (1068, 'Linie'),
    'total_text':          (1069, 'Znaki'),
    'fdscript_hint':       (1070, '# Kod FDScript tutaj...'),
    'prefix_label':        (1071, 'Prefiks'),
    'prefix_hint':         (1072, 'Przykład: !cmd'),
    'search':              (1073, 'Szukaj'),
    'commands':            (1074, 'Komendy'),
    'no_cmds_hint':        (1075, 'Nie znaleziono komend. Kliknij +, aby ją utworzyć.'),
    'del':                 (1076, 'Usuń'),
    'name_required':       (1077, 'Nazwa jest wymagana'),
    'delete_q':            (1078, 'Usunąć?'),
    'delete_confirm':      (1079, 'Czy na pewno chcesz usunąć "{item_name}"?\nTej operacji nie można cofnąć.'),
    'dest_event':          (1080, 'Zdarzenie'),
    'dest_cmd':            (1081, 'Komenda'),
    'commands_label':      (1082, 'Wpisz nazwę komendy'),
    'unsaved_title':       (1083, 'Niezapisane zmiany'),
    'unsaved_body':        (1084, 'Istnieją niezapisane zmiany. Czy chcesz je zapisać przed wyjściem?'),
    'discard':             (1085, 'Odrzuć'),
    'loading':             (1086, 'Ładowanie...'),

    # ── wiki_view ─────────────────────────────────────────────
    'search_hint':          (1122, 'Szukaj funkcji...'),
    'check_updates':        (1123, 'Sprawdź aktualizacje'),
    'checking':             (1124, 'Sprawdzanie...'),
    'downloading':          (1125, 'Pobieranie wiki...'),
    'up_to_date':           (1126, 'Wiki jest aktualne (v{v})'),
    'update_available':     (1127, 'Dostępna nowa aktualizacja (v{v})'),
    'update_failed':        (1128, 'Nie udało się sprawdzić aktualizacji'),
    'no_cache':             (1129, 'Brak lokalnych danych. Naciśnij "Sprawdź aktualizacje".'),
    'no_results':           (1130, 'Brak wyników'),
    'function_info':        (1131, 'Informacje o funkcji'),
    'no_details':           (1132, 'Brak dostępnych szczegółów'),
    'open_dashboard':       (1133, 'Otwórz panel'),
    'copy_syntax':          (1134, 'Kopiuj'),
    'copied':               (1135, 'Skopiowano!'),
    'syntax':               (1136, 'Składnia'),
    'parameters':           (1137, 'Parametry'),
    'example':              (1138, 'Przykład'),
    'notes':                (1139, 'Uwagi'),
    'warnings':             (1140, 'Ostrzeżenia'),
    'required':             (1141, 'Wymagane'),
    'optional':             (1142, 'Opcjonalne'),
    'not_used_in_bot':      (1143, 'Ta funkcja nie jest używana w komendach tego bota'),

    # ── wiki_view filters ─────────────────────────────────────
    'filter_all':           (1148, 'Wszystko'),
    'filter_command':       (1149, 'Komenda'),
    'filter_event':         (1150, 'Zdarzenie'),
    'filter_variable':      (1171, 'Zmienne'),
    'filter_discord':       (1172, 'Discord'),
    'filter_time':          (1173, 'Czas'),
    'filter_other':         (1174, 'Inne'),
    'filter_title':         (1241, 'Kategorie'),
    'filter_tooltip':       (1246, 'Filtr'),
    'no_categories':        (1247, 'Brak kategorii'),

    # ── wiki_view callouts ────────────────────────────────────
    'callout_note':         (1144, 'Uwaga'),
    'callout_limit':        (1145, 'Limit'),
    'callout_important':    (1146, 'To ważne!'),
    'callout_question':     (1147, 'Co to jest?'),

    # ── variables_view ────────────────────────────────────────
    'variables':            (1028, 'Zmienne'),
    'variables_slash':      (1151, 'Zmienne /'),
    'scoped_vars':          (1152, 'Wartości dla poszczególnych użytkowników'),
    'value_label':          (1153, 'Wartość'),
    'var_name_hint':        (1154, 'nazwa_zmiennej'),
    'var_value_hint':       (1155, 'wartość_zmiennej'),
    'info_var':             (1156, 'Informacje o zmiennej'),
    'invalid_json':         (1157, 'Nieprawidłowy JSON'),
    'json_must_be_object':  (1158, 'Wartość najwyższego poziomu musi być obiektem JSON ({"userID": "value"}).'),
    'no_variables':         (1089, 'Brak zmiennych'),
    'enter_variable_name':  (1106, 'Wpisz nazwę zmiennej'),

    # ── App Updater ───────────────────────────────────────────
    'app_update_title':           (1159, 'Dostępna aktualizacja'),
    'app_update_new_version':     (1160, 'Nowa wersja'),
    'app_update_current_version': (1161, 'Obecna'),
    'app_update_no_changelog':    (1162, 'Brak listy zmian dla tej aktualizacji.'),
    'app_update_later':           (1163, 'Później'),
    'app_update_now':             (1164, 'Aktualizuj teraz'),
    'app_update_downloading':     (1165, 'Pobieranie'),
    'app_update_done':            (1166, 'Pobieranie zakończone ✓'),
    'app_update_failed':          (1167, 'Pobieranie nie powiodło się'),
    'app_update_open_installer':  (1168, 'Otwórz instalator'),
    'app_update_installer_opened':(1169, 'Instalator otwarty. Dokończ instalację, a następnie ponownie otwórz aplikację.'),
    'app_update_open_failed':     (1170, 'Nie można otworzyć pliku instalacyjnego'),

    # ── Status Bot View ───────────────────────────────────────
    'status_bot_section':         (1175, 'Status bota'),
    'status_bot_desc':            (1176, 'Skonfiguruj obecność bota i rotujące wiadomości statusu'),
    'open_status_bot':            (1177, 'Zarządzaj statusem'),
    'status_bot_title':           (1178, 'Bot statusu'),
    'sv_status_label':            (1179, 'Status'),
    'sv_loop_time_label':         (1180, 'Czas cyklu'),
    'sv_loop_time_seconds':       (1181, 'Sekundy'),
    'sv_loop_time_hint':          (1182, 'Tylko liczby całkowite, min. 12 sekund'),
    'sv_activate_presence':       (1183, 'Włącz obecność bota'),
    'sv_status_entries':          (1184, 'Wpisy statusu'),
    'sv_add_entry':               (1185, 'Dodaj nowy wpis'),
    'sv_entry_details_ph':        (1186, 'Szczegóły statusu'),
    'sv_status_online':           (1187, 'Online'),
    'sv_status_idle':             (1188, 'Zaraz wracam'),
    'sv_status_dnd':              (1189, 'Nie przeszkadzać'),
    'sv_status_invisible':        (1190, 'Niewidoczny'),
    'sv_create_edit_title':       (1191, 'Utwórz lub edytuj wpis statusu'),
    'sv_status_data':             (1192, 'Dane statusu'),
    'sv_prefix_status':           (1193, 'Prefiks statusu'),
    'sv_status_field':            (1194, 'Status'),
    'sv_status_details':          (1195, 'Szczegóły statusu'),
    'sv_prefix_hint':             (1196, 'np. Gra w'),
    'sv_status_hint':             (1197, 'Krótki tekst statusu'),
    'sv_details_hint':            (1198, 'Dodatkowe szczegóły wyświetlane pod statusem'),
    'sv_preview':                 (1199, 'Podgląd'),
    'sv_name_bot':                (1200, 'Nazwa bota'),
    'sv_app_badge':               (1201, 'APP'),
    'sv_save_entry':              (1202, 'Zapisz wpis'),
    'sv_back':                    (1203, 'Wstecz'),
    'sv_no_entries':              (1204, 'Brak wpisów statusu.'),
    'sv_unit_second':             (1205, 'Sekunda'),
    'sv_unit_minute':             (1206, 'Minuta'),
    'sv_unit_hour':               (1207, 'Godzina'),
    'sv_unit_day':                (1208, 'Dzień'),
    'sv_loop_time_integer_error': (1209, 'Tylko liczby całkowite — bez ułamków i symboli'),
    'sv_loop_time_min_error':     (1210, 'Czas cyklu nie może być krótszy niż 12 sekund'),
    'sv_activity_type':           (1211, 'Typ aktywności'),
    'sv_activity_playing':        (1212, 'Gra w'),
    'sv_activity_streaming':      (1213, 'Transmituje'),
    'sv_activity_listening':      (1214, 'Słucha'),
    'sv_activity_watching':       (1215, 'Ogląda'),
    'sv_activity_competing':      (1216, 'Rywalizuje w'),
    'sv_stream_url':              (1217, 'Adres URL transmisji'),
    'sv_stream_url_hint':         (1218, 'https://twitch.tv/... lub https://youtube.com/...'),
    'sv_stream_url_required':     (1219, 'Adres URL transmisji jest wymagany dla statusu Transmisja'),
    'sv_stream_url_invalid':      (1220, 'Dozwolone są tylko linki Twitch lub YouTube'),
    'sv_help_note_title':         (1229, 'Uwagi'),
    'sv_help_note_body':          (1230, 'Wprowadzenie zmian chwilę trwa. Dodanie, edycja lub usunięcie statusu '
                                      '— oraz włączanie i wyłączanie obecności — podczas działania bota nie '
                                      'zostanie zastosowane natychmiast. Bot najpierw kończy przewijanie bieżącej '
                                      'listy, więc wyświetlenie zmiany może chwilę potrwać.'),

    # ── Create Bot — Import from backup ────────────────────────────────────
    'import_zip_btn':           (1221, 'Przywróć z kopii zapasowej'),
    'import_zip_disabled_hint': (1222, 'Najpierw ustaw nazwę bota i poprawny token'),
    'import_zip_selected':      (1223, 'Wybrano kopię zapasową: {file_name}'),
    'import_zip_clear':         (1224, 'Usuń'),
    'import_zip_invalid':       (1225, 'To nie wygląda na plik kopii zapasowej bota'),
    'import_zip_pick_title':    (1226, 'Wybierz plik ZIP kopii zapasowej'),
    'import_zip_applied':       (1227, 'Bot utworzony, a kopia zapasowa przywrócona!'),
    'import_zip_failed':        (1228, 'Bot został utworzony, ale przywracanie kopii zapasowej nie powiodło się'),

    # ── General Actions & Feedback ─────────────────────────────────────────
    'edit':                   (1094, 'Edytuj'),
    'delete':                 (1095, 'Usuń'),
    'cancel':                 (1100, 'Anuluj'),
    'reset':                  (1242, 'Resetuj'),
    'close':                  (1243, 'Zamknij'),
    'done':                   (1244, 'Gotowe'),
    'clear_search':           (1245, 'Wyczyść wyszukiwanie'),
    'saved_successfully':     (1231, 'Zapisano pomyślnie'),

    # ── Mobile Warning ────────────────────────────────────────────────────
    'mobile_warn_title':      (1232, 'Uwaga dotycząca działania w tle na urządzeniach mobilnych'),
    'mobile_warn_body':       (1233, 'Uruchamianie botów na systemach mobilnych (tylko Android) podlega ścisłym ograniczeniom działania w tle nakładanym przez system operacyjny.\n\n• W najlepszym przypadku bot może działać w tle maksymalnie do 6 godzin.\n• Musisz wyłączyć optymalizację baterii (ustawić na "Bez ograniczeń") w ustawieniach urządzenia.\n• Niektóre urządzenia mogą natychmiast zawiesić działanie bota po zminimalizowaniu aplikacji.\n\nUruchamianie botów na hostingu/serwerze/VPS itp. nie jest jeszcze obsługiwane.'),

    # ── Command Editor Syntax Warning ─────────────────────────────────────
    'syntax_warn_banner':     (1234, 'Tryb kolorów jest aktywny. W przypadku dużych plików (>2000 znaków) wyłącz tryb kolorów, aby uniknąć spowolnienia urządzenia.'),
    'syntax_limit_refusal':   (1235, 'Nie można włączyć trybu kolorów: tekst przekracza limit 2000 znaków ustanowiony w celu ochrony wydajności.'),
    'syntax_color_label':     (1236, 'Kolor'),

    # ── Total Counts ──────────────────────────────────────────────────────
    'total_bots_count':       (1237, 'Liczba posiadanych botów: {count}'),
    'total_vars_count':       (1238, 'Liczba zmiennych: {count}'),
    'total_cmds_count':       (1239, 'Liczba komend: {count}'),
    'total_wiki_count':       (1240, 'Wyniki: {count}'),

    # ── Token Verification ────────────────────────────────────────────────
    'verify_token':           (1248, 'Zweryfikuj token'),
    'verifying':              (1249, 'Weryfikowanie...'),
    'token_valid':            (1250, 'Połączenie udane! Token jest prawidłowy.'),
    'token_invalid':          (1251, 'Nieprawidłowy token lub połączenie nie powiodło się.'),

    # ── Android Background Notification ────────────────────────────────────
    'fgs_state_working':          (1252, 'Bot działa | 🟢'),
    'server_status_online':       (1257, 'Serwer online: {name}'),
    'server_status_stopped':      (1258, 'Serwer zatrzymany'),
    'fgs_limit_reached':          (1259, 'Osiągnięto limit działania w tle na Androidzie (6 godzin). Otwórz aplikację, aby ponownie uruchomić serwer.'),
    'fgs_start_failed':           (1260, 'Nie udało się uruchomić usługi w tle: {error}'),

    # ── Privileged Gateway Intents Warning ────────────────────────────────
    'intents_warning_title':      (1261, 'Uprzywilejowane intencje wyłączone'),
    'intents_warning_msg':        (1262, 'Ostrzeżenie: uprzywilejowane intencje bramy (obecność, członkowie, zawartość wiadomości) nie są włączone w portalu deweloperskim Discord. Komendy i zdarzenia mogą nie działać poprawnie.'),
    'open_dev_portal':            (1263, 'Włącz w portalu'),

    'syntax_switch_tooltip': (1264, 'Przełącz podświetlanie składni'),
    'new_command_file':      (1265, 'Nowy.fds'),
    'wiki_events_tooltip':   (1266, 'Wiki: Zdarzenia'),
    'new_variable_file':     (1267, 'nowy.json'),
    'scoped_json_title':     (1268, '{name} — Dane JSON dla użytkowników'),
}