# -*- coding: utf-8 -*-
# main_app/langs/ch.py

CHINESE_DICT = {
    # ── 主介面 ────────────────────────────────────
    'main_title':          (1001, 'FDSB'),
    'no_bots_hint':        (1002, '未找到機器人。點擊「新增機器人」來建立一個。'),
    'new_bot':             (1003, '新增機器人'),
    'discord':             (1004, 'Discord'),
    'github':              (1005, 'GitHub'),

    # ── 機器人建立視窗 ────────────────────────────────
    'name_label':          (1006, '名稱'),
    'token_label':         (1007, 'Token'),
    'name_hint':           (1008, '輸入機器人名稱'),
    'token_hint':          (1009, '輸入機器人 Token'),
    'make':                (1010, '建立'),
    'image_label':         (1011, '圖片'),
    'ok':                  (1012, '確定'),
    'token_required':      (1013, '需要 Token'),
    'name_taken':          (1014, '名稱已被使用\n請選擇其他名稱'),

    # ── 機器人控制面板 ─────────────────────────────────────────
    'state_server':        (1015, '伺服器狀態'),
    'online':              (1016, '上線'),
    'offline':             (1017, '離線'),
    'start':               (1018, '啟動'),
    'stop':                (1019, '停止'),
    'whats_new':           (1020, '最新消息'),
    'no_updates':          (1021, '沒有可用的更新。'),
    'no_file':             (1022, '找不到更新檔案。'),
    'read_error':          (1023, '無法讀取檔案。'),
    'invite_bot':          (1024, '邀請機器人'),
    'back':                (1025, '返回'),
    'main_tab':            (1026, '主頁'),
    'commands_tab':        (1027, '指令'),
    'variables':           (1028, '變數'),
    'settings':            (1029, '設定'),
    'avatar_none':         (1030, '無頭像'),
    'tab_main':            (1117, '主頁'),
    'tab_commands':        (1118, '指令'),
    'tab_variables':       (1119, '變數'),
    'tab_settings':        (1120, '設定'),

    # ── 設定 ─────────────────────────────────────────
    'general_section':     (1031, '一般'),
    'design_section':      (1032, '外觀'),
    'info_section':        (1033, '資訊'),
    'name_project':        (1034, '專案名稱'),
    'token_field':         (1035, '機器人 Token'),
    'bot_name_hint':       (1036, '機器人名稱'),
    'bot_token_hint':      (1037, '機器人 Token'),
    'save':                (1038, '儲存'),
    'language':            (1039, '語言'),
    'wiki':                (1040, 'Wiki'),
    'link':                (1041, '(連結)'),
    'restart_notice':      (1042, '重新啟動中...'),

    # ── 匯出資料 ─────────────────────────────────────
    'export_section':      (1043, '匯出資料'),
    'export_desc':         (1044, '將指令與變數匯出為 ZIP 檔案'),
    'export_zip':          (1045, '匯出為 ZIP'),
    'no_bot_selected':     (1046, '未選擇機器人！'),
    'folders_not_found':   (1047, '找不到資料夾！'),
    'export_failed':       (1048, '匯出失敗！'),
    'export_success':      (1232, '匯出成功！'),

    # ── 危險區域 / 刪除 ────────────────────────────────
    'danger_zone':         (1049, '危險區域'),
    'delete_bot_perm':     (1050, '永久刪除此機器人'),
    'captcha_enter':       (1051, '輸入 3 位數字'),
    'captcha_hint':        (1052, '請輸入上方顯示的 3 位數字'),
    'confirm_delete':      (1053, '確認刪除'),
    'captcha_wrong':       (1054, '代碼錯誤 — 請重試'),

    # ── 主題名稱 ───────────────────────────────────────────
    'system_wh':           (1055, '系統 (淺色)'),
    'system_da':           (1056, '系統 (深色)'),
    'blue_sky':            (1057, '藍色 - 天空'),
    'yellow_bile':         (1058, '黃色 - 金色'),
    'v2_dark':             (1059, '深金色'),

    # ── 指令視圖 ─────────────────────────────────────────
    'commands_slash':      (1060, '/ 指令'),
    'info_command':        (1061, '指令資訊'),
    'command_editor':      (1062, '指令編輯器'),
    'total_lines':         (1063, '行數'),
    'total_text':          (1064, '字元數'),
    'fdscript_hint':       (1065, '# 在此輸入 FDScript 程式碼...'),
    'prefix_label':        (1066, '前綴'),
    'prefix_hint':         (1067, '範例: !cmd'),
    'search':              (1068, '搜尋'),
    'commands':            (1069, '指令'),
    'no_cmds_hint':        (1070, '沒有指令。點擊 + 來建立一個。'),
    'del':                 (1071, '刪除'),
    'name_required':       (1072, '需要名稱'),
    'delete_q':            (1073, '確定刪除？'),
    'delete_confirm':      (1074, '你確定要刪除 "{item_name}" 嗎？\n此動作無法還原。'),
    'dest_event':          (1075, '事件'),
    'dest_cmd':            (1076, '指令'),
    'commands_label':      (1077, '輸入指令名稱'),
    'unsaved_title':       (1113, '未儲存的變更'),
    'unsaved_body':        (1114, '有未儲存的變更。你想在離開前儲存嗎？'),
    'discard':             (1115, '放棄'),

    # ── 舊有鍵值 ────────────────────────────────────────
    'create_file':         (1116, '建立新檔案'),
    'bot_token':           (1078, '機器人 Token'),
    'start_server':        (1079, '啟動伺服器'),
    'stop_server':         (1080, '停止伺服器'),
    'files_list':          (1081, '檔案列表'),
    'run':                 (1082, '執行'),
    'file_name':           (1083, '檔案名稱'),
    'file_content':        (1084, '檔案內容'),
    'variable_name':       (1085, '變數名稱'),
    'variable_value':      (1086, '變數值'),
    'add_variable':        (1087, '新增變數'),
    'no_files':            (1088, '沒有檔案'),
    'no_variables':        (1089, '沒有變數'),
    'enter_token':         (1090, '輸入機器人 Token'),
    'server_status':       (1091, '伺服器狀態'),
    'running':             (1092, '執行中'),
    'stopped':             (1093, '已停止'),
    'edit':                (1094, '編輯'),
    'delete':              (1095, '刪除'),
    'new_file':            (1096, '新檔案'),
    'arabic':              (1097, '阿拉伯語'),
    'english':             (1098, '英語'),
    'confirm':             (1099, '確認'),
    'cancel':              (1100, '取消'),
    'success':             (1101, '成功'),
    'error':               (1102, '錯誤'),
    'file_saved':          (1103, '檔案已儲存'),
    'variable_added':      (1104, '變數已新增'),
    'enter_file_name':     (1105, '輸入檔案名稱'),
    'enter_variable_name': (1106, '輸入變數名稱'),
    'file_prefix':         (1107, '檔案前綴'),
    'enter_prefix':        (1108, '輸入前綴'),
    'prefix':              (1109, '前綴'),
    'edit_prefix':         (1110, '編輯前綴'),
    'prefix_updated':      (1111, '前綴已更新'),
    'toggle_language':     (1112, 'English'),

    # ── Wiki ─────────────────────────────────────────────────
    'tab_wiki':             (1121, 'Wiki'),
    'search_hint':          (1122, '搜索功能...'),
    'check_updates':        (1123, '检查更新'),
    'checking':             (1124, '检查中...'),
    'downloading':          (1125, '正在下载 Wiki...'),
    'up_to_date':           (1126, 'Wiki 已是最新 (v{v})'),
    'update_available':     (1127, '有新更新可用 (v{v})'),
    'update_failed':        (1128, '检查更新失败'),
    'no_cache':             (1129, '暂无本地数据。请点击"检查更新"。'),
    'no_results':           (1130, '无结果'),
    'function_info':        (1131, '功能信息'),
    'no_details':           (1132, '无可用详情'),
    'open_dashboard':       (1133, '打开仪表盘'),
    'copy_syntax':          (1134, '复制'),
    'copied':               (1135, '已复制！'),
    'syntax':               (1136, '语法'),
    'parameters':           (1137, '参数'),
    'example':              (1138, '示例'),
    'notes':                (1139, '备注'),
    'warnings':             (1140, '警告'),
    'required':             (1141, '必填'),
    'optional':             (1142, '可选'),
    'not_used_in_bot':      (1143, '此功能未在此机器人的命令中使用'),
    'callout_note':         (1144, '注意'),
    'callout_limit':        (1145, '限制'),
    'callout_important':    (1146, '重要！'),
    'callout_question':     (1147, '这是什么？'),
    'filter_all':           (1148, '全部'),
    'filter_command':       (1149, '指令'),
    'filter_event':         (1150, '事件'),

    # ── variables_view ────────────────────────────────────────
    'variables_slash':      (1151, '變數 /'),
    'scoped_vars':          (1152, '每位用戶的值'),
    'value_label':          (1153, '值'),
    'var_name_hint':        (1154, 'variable_name'),
    'var_value_hint':       (1155, 'variable_value'),
    'info_var':             (1156, '變數資訊'),
    'invalid_json':         (1157, '無效的 JSON'),
    'json_must_be_object':  (1158, '頂層值必須是 JSON 物件 ({"userID": "value"}).'),

    # ── 应用更新 ───────────────────────────────────────
    'app_update_title':          (1159, '有可用更新'),
    'app_update_new_version':    (1160, '新版本'),
    'app_update_current_version':(1161, '当前'),
    'app_update_no_changelog':   (1162, '此更新没有可用的更新日志。'),
    'app_update_later':          (1163, '稍后'),
    'app_update_now':            (1164, '立即更新'),
    'app_update_downloading':    (1165, '下载中'),
    'app_update_done':           (1166, '下载完成 ✓'),
    'app_update_failed':         (1167, '下载失败'),
    'app_update_open_installer': (1168, '打开安装程序'),
    'app_update_installer_opened':(1169, '安装程序已打开。完成安装后，请重新打开应用。'),
    'app_update_open_failed':    (1170, '无法打开安装程序文件'),

    # ── wiki_view filters (extended) ─────────────────────────
    'filter_variable':      (1171, '变量'),
    'filter_discord':       (1172, 'Discord'),
    'filter_time':          (1173, '时间'),
    'filter_other':         (1174, '其他'),

    # ── 機器人狀態檢視 ───────────────────────────────
    'status_bot_section':   (1175, '機器人狀態'),
    'status_bot_desc':      (1176, '設定機器人的在線狀態與輪播狀態訊息'),
    'open_status_bot':      (1177, '管理狀態'),
    'status_bot_title':     (1178, '機器人狀態'),
    'sv_status_label':      (1179, '狀態'),
    'sv_loop_time_label':   (1180, '輪播時間'),
    'sv_loop_time_seconds': (1181, '秒'),
    'sv_loop_time_hint':    (1182, '僅限整數，最少 12 秒'),
    'sv_activate_presence': (1183, '正在啟用機器人狀態'),
    'sv_status_entries':    (1184, '狀態項目'),
    'sv_add_entry':         (1185, '新增項目'),
    'sv_entry_details_ph':  (1186, '狀態詳情'),
    'sv_status_online':     (1187, '上線'),
    'sv_status_idle':       (1188, '閒置'),
    'sv_status_dnd':        (1189, '請勿打擾'),
    'sv_status_invisible':  (1190, '隱形'),
    'sv_create_edit_title': (1191, '建立或編輯狀態項目'),
    'sv_status_data':       (1192, '狀態資料'),
    'sv_prefix_status':     (1193, '狀態前綴'),
    'sv_status_field':      (1194, '狀態'),
    'sv_status_details':    (1195, '狀態詳情'),
    'sv_prefix_hint':       (1196, '例如: 正在玩'),
    'sv_status_hint':       (1197, '簡短的狀態文字'),
    'sv_details_hint':      (1198, '顯示在狀態下方的額外詳情'),
    'sv_preview':           (1199, '預覽'),
    'sv_name_bot':          (1200, '機器人名稱'),
    'sv_app_badge':         (1201, 'APP'),
    'sv_save_entry':        (1202, '儲存項目'),
    'sv_back':              (1203, '返回'),
    'sv_no_entries':        (1204, '尚無狀態項目。'),
    'sv_unit_second':       (1205, '秒'),
    'sv_unit_minute':       (1206, '分鐘'),
    'sv_unit_hour':         (1207, '小時'),
    'sv_unit_day':          (1208, '天'),
    'sv_loop_time_integer_error': (1209, '僅限整數 — 不能有小數點或符號'),
    'sv_loop_time_min_error':     (1210, '輪播時間不能少於 12 秒'),
    'sv_activity_type':      (1211, '活動類型'),
    'sv_activity_playing':   (1212, '正在玩'),
    'sv_activity_streaming': (1213, '直播中'),
    'sv_activity_listening': (1214, '正在聽'),
    'sv_activity_watching':  (1215, '正在看'),
    'sv_activity_competing': (1216, '正在參加'),
    'sv_stream_url':          (1217, '直播連結'),
    'sv_stream_url_hint':     (1218, 'https://twitch.tv/... 或 https://youtube.com/...'),
    'sv_stream_url_required': (1219, '直播狀態需要提供直播連結'),
    'sv_stream_url_invalid':  (1220, '只允許使用 Twitch 或 YouTube 連結'),
    'sv_help_note_title':     (1229, '備註'),
    'sv_help_note_body':      (1230, '變更需要一點時間才會生效。在機器人執行時新增、編輯或刪除'
                                      '狀態——以及開啟或關閉在線狀態——不會立即套用。機器人會先完成'
                                      '目前清單的輪播，因此可能需要一段時間您的更新才會顯示。'),

    # ── 建立機器人 — 從備份匯入 ────────────────────────────
    'import_zip_btn':         (1221, '從備份還原'),
    'import_zip_disabled_hint': (1222, '請先設定機器人名稱和有效的 Token'),
    'import_zip_selected':    (1223, '已選擇備份: {file_name}'),
    'import_zip_clear':       (1224, '移除'),
    'import_zip_invalid':     (1225, '這似乎不是機器人備份檔案'),
    'import_zip_pick_title':  (1226, '選擇備份 ZIP 檔案'),
    'import_zip_applied':     (1227, '機器人已建立並還原備份！'),
    'import_zip_failed':      (1228, '機器人已建立，但還原備份失敗'),

    # ── 儲存回饋 ──────────────────────────────────────────
    'saved_successfully':     (1231, '儲存成功'),

    # ── 手機背景警告 ─────────────────────────────────────
    'mobile_warn_title':      (1232, '手機背景執行通知'),
    'mobile_warn_body':       (1233, '在手機系統（僅限 Android）上執行機器人會受到嚴格的主機背景限制。\n\n• 在最佳情況下，機器人最多只能在背景執行 6 小時。\n• 您必須在裝置設定中停用電池最佳化（設為「不受限制」）。\n• 某些裝置可能會在最小化時立即暫停機器人。\n\n關於在主機/伺服器/VPS 或類似環境上執行機器人，目前尚不支援。'),

    # ── 指令編輯器語法警告 ──────────────────────────────
    'syntax_warn_banner':     (1234, '色彩模式已啟用。對於大型檔案（超過 2000 字元），請關閉色彩模式以避免裝置延遲。'),
    'syntax_limit_refusal':   (1235, '無法啟用色彩模式：文字超過 2000 字元限制以保護效能。'),
    'syntax_color_label':     (1236, '色彩'),

    # ── 總計數 ─────────────────────────────────────────
    'total_bots_count':       (1237, '您擁有的機器人總數：{count}'),
    'total_vars_count':       (1238, '變數總數：{count}'),
    'total_cmds_count':       (1239, '指令總數：{count}'),
    'total_wiki_count':       (1240, '結果：{count}'),

    # ── 維基篩選表（擴充） ─────────────────────────────
    'filter_title':          (1241, '類別'),
    'reset':                 (1242, '重設'),
    'close':                 (1243, '關閉'),
    'done':                  (1244, '完成'),
    'clear_search':          (1245, '清除搜尋'),
    'filter_tooltip':        (1246, '篩選'),
    'no_categories':         (1247, '尚無類別'),
    'verify_token':          (1248, '驗證 Token'),
    'verifying':             (1249, '驗證中...'),
    'token_valid':           (1250, '連線成功！Token 有效。'),
    'token_invalid':         (1251, 'Token 無效或連線失敗。'),
}
