# -*- coding: utf-8 -*-
# main_app/langs/de.py

GERMAN_DICT = {
    # ── Hauptschnittstelle ────────────────────────────────────
    'main_title':          (1001, 'FDSB'),
    'no_bots_hint':        (1002, 'Keine Bots gefunden. Klicken Sie auf "Neuer Bot", um einen zu erstellen.'),
    'new_bot':             (1003, 'Neuer Bot'),
    'discord':             (1004, 'Discord'),
    'github':              (1005, 'GitHub'),

    # ── Bot-Erstellungsfenster ────────────────────────────────
    'name_label':          (1006, 'Name'),
    'token_label':         (1007, 'Token'),
    'name_hint':           (1008, 'Bot-Namen eingeben'),
    'token_hint':          (1009, 'Bot-Token eingeben'),
    'make':                (1010, 'Erstellen'),
    'image_label':         (1011, 'Bild'),
    'ok':                  (1012, 'OK'),
    'token_required':      (1013, 'Token ist erforderlich'),
    'name_taken':          (1014, 'Name bereits vergeben\nWählen Sie einen anderen Namen'),

    # ── Bot-Dashboard ─────────────────────────────────────────
    'state_server':        (1015, 'Serverstatus'),
    'online':              (1016, 'Online'),
    'offline':             (1017, 'Offline'),
    'start':               (1018, 'Starten'),
    'stop':                (1019, 'Stoppen'),
    'whats_new':           (1020, 'Was ist neu'),
    'no_updates':          (1021, 'Keine Updates verfügbar.'),
    'no_file':             (1022, 'Update-Datei nicht gefunden.'),
    'read_error':          (1023, 'Datei konnte nicht gelesen werden.'),
    'invite_bot':          (1024, 'Bot einladen'),
    'back':                (1025, 'Zurück'),
    'main_tab':            (1026, 'Hauptseite'),
    'commands_tab':        (1027, 'Befehle'),
    'variables':           (1028, 'Variablen'),
    'settings':            (1029, 'Einstellungen'),
    'avatar_none':         (1030, 'Kein Avatar'),
    'tab_main':            (1117, 'Hauptseite'),
    'tab_commands':        (1118, 'Befehle'),
    'tab_variables':       (1119, 'Variablen'),
    'tab_settings':        (1120, 'Einstellungen'),

    # ── Einstellungen ─────────────────────────────────────────
    'general_section':     (1031, 'Allgemein'),
    'design_section':      (1032, 'Design'),
    'info_section':        (1033, 'Informationen'),
    'name_project':        (1034, 'Projektname'),
    'token_field':         (1035, 'Bot-Token'),
    'bot_name_hint':       (1036, 'Bot-Name'),
    'bot_token_hint':      (1037, 'Bot-Token'),
    'save':                (1038, 'Speichern'),
    'language':            (1039, 'Sprache'),
    'wiki':                (1040, 'Wiki'),
    'link':                (1041, '(Link)'),
    'restart_notice':      (1042, 'Wird neu gestartet...'),

    # ── Daten exportieren ─────────────────────────────────────
    'export_section':      (1043, 'Daten exportieren'),
    'export_desc':         (1044, 'Befehle und Variablen als ZIP-Datei exportieren'),
    'export_zip':          (1045, 'Als ZIP exportieren'),
    'no_bot_selected':     (1046, 'Kein Bot ausgewählt!'),
    'folders_not_found':   (1047, 'Ordner nicht gefunden!'),
    'export_failed':       (1048, 'Export fehlgeschlagen!'),
    'export_success':      (1232, 'Erfolgreich exportiert!'),

    # ── Gefahrenzone / Löschen ────────────────────────────────
    'danger_zone':         (1049, 'Gefahrenzone'),
    'delete_bot_perm':     (1050, 'Diesen Bot dauerhaft löschen'),
    'captcha_enter':       (1051, '3 Ziffern eingeben'),
    'captcha_hint':        (1052, 'Geben Sie die 3 oben gezeigten Ziffern ein'),
    'confirm_delete':      (1053, 'Löschen bestätigen'),
    'captcha_wrong':       (1054, 'Falscher Code — Erneut versuchen'),

    # ── Theme-Namen ───────────────────────────────────────────
    'system_wh':           (1055, 'System (Hell)'),
    'system_da':           (1056, 'System (Dunkel)'),
    'blue_sky':            (1057, 'Blau - Himmel'),
    'yellow_bile':         (1058, 'Gelb - Gold'),
    'v2_dark':             (1059, 'Dunkles Gold'),

    # ── commands_view ─────────────────────────────────────────
    'commands_slash':      (1060, '/ Befehle'),
    'info_command':        (1061, 'Befehlsinfo'),
    'command_editor':      (1062, 'Befehlseditor'),
    'total_lines':         (1063, 'Zeilen'),
    'total_text':          (1064, 'Zeichen'),
    'fdscript_hint':       (1065, '# FDScript-Code hier...'),
    'prefix_label':        (1066, 'Präfix'),
    'prefix_hint':         (1067, 'Beispiel: !cmd'),
    'search':              (1068, 'Suchen'),
    'commands':            (1069, 'Befehle'),
    'no_cmds_hint':        (1070, 'Keine Befehle. Klicken Sie auf +, um einen zu erstellen.'),
    'del':                 (1071, 'Löschen'),
    'name_required':       (1072, 'Name ist erforderlich'),
    'delete_q':            (1073, 'Löschen?'),
    'delete_confirm':      (1074, 'Möchten Sie "{item_name}" wirklich löschen?\nDiese Aktion kann nicht rückgängig gemacht werden.'),
    'dest_event':          (1075, 'Ereignis'),
    'dest_cmd':            (1076, 'Befehl'),
    'commands_label':      (1077, 'Befehlsnamen eingeben'),
    'unsaved_title':       (1113, 'Ungespeicherte Änderungen'),
    'unsaved_body':        (1114, 'Es gibt ungespeicherte Änderungen. Möchten Sie diese vor dem Verlassen speichern?'),
    'discard':             (1115, 'Verwerfen'),

    # ── Alte Schlüssel ────────────────────────────────────────
    'create_file':         (1116, 'Neue Datei erstellen'),
    'bot_token':           (1078, 'Bot-Token'),
    'start_server':        (1079, 'Server starten'),
    'stop_server':         (1080, 'Server stoppen'),
    'files_list':          (1081, 'Dateiliste'),
    'run':                 (1082, 'Ausführen'),
    'file_name':           (1083, 'Dateiname'),
    'file_content':        (1084, 'Dateiinhalt'),
    'variable_name':       (1085, 'Variablenname'),
    'variable_value':      (1086, 'Variablenwert'),
    'add_variable':        (1087, 'Variable hinzufügen'),
    'no_files':            (1088, 'Keine Dateien'),
    'no_variables':        (1089, 'Keine Variablen'),
    'enter_token':         (1090, 'Bot-Token eingeben'),
    'server_status':       (1091, 'Serverstatus'),
    'running':             (1092, 'Läuft'),
    'stopped':             (1093, 'Gestoppt'),
    'edit':                (1094, 'Bearbeiten'),
    'delete':              (1095, 'Löschen'),
    'new_file':            (1096, 'Neue Datei'),
    'arabic':              (1097, 'Arabisch'),
    'english':             (1098, 'Englisch'),
    'confirm':             (1099, 'Bestätigen'),
    'cancel':              (1100, 'Abbrechen'),
    'success':             (1101, 'Erfolg'),
    'error':               (1102, 'Fehler'),
    'file_saved':          (1103, 'Datei gespeichert'),
    'variable_added':      (1104, 'Variable hinzugefügt'),
    'enter_file_name':     (1105, 'Dateinamen eingeben'),
    'enter_variable_name': (1106, 'Variablennamen eingeben'),
    'file_prefix':         (1107, 'Dateipräfix'),
    'enter_prefix':        (1108, 'Präfix eingeben'),
    'prefix':              (1109, 'Präfix'),
    'edit_prefix':         (1110, 'Präfix bearbeiten'),
    'prefix_updated':      (1111, 'Präfix aktualisiert'),
    'toggle_language':     (1112, 'English'),

    # ── Wiki ─────────────────────────────────────────────────
    'tab_wiki':             (1121, 'Wiki'),
    'search_hint':          (1122, 'Funktion suchen...'),
    'check_updates':        (1123, 'Auf Updates prüfen'),
    'checking':             (1124, 'Überprüfung...'),
    'downloading':          (1125, 'Wiki wird heruntergeladen...'),
    'up_to_date':           (1126, 'Wiki ist aktuell (v{v})'),
    'update_available':     (1127, 'Neues Update verfügbar (v{v})'),
    'update_failed':        (1128, 'Update-Überprüfung fehlgeschlagen'),
    'no_cache':             (1129, 'Noch keine lokalen Daten. Auf "Auf Updates prüfen" klicken.'),
    'no_results':           (1130, 'Keine Ergebnisse'),
    'function_info':        (1131, 'Funktionsinfo'),
    'no_details':           (1132, 'Keine Details verfügbar'),
    'open_dashboard':       (1133, 'Dashboard öffnen'),
    'copy_syntax':          (1134, 'Kopieren'),
    'copied':               (1135, 'Kopiert!'),
    'syntax':               (1136, 'Syntax'),
    'parameters':           (1137, 'Parameter'),
    'example':              (1138, 'Beispiel'),
    'notes':                (1139, 'Hinweise'),
    'warnings':             (1140, 'Warnungen'),
    'required':             (1141, 'Erforderlich'),
    'optional':             (1142, 'Optional'),
    'not_used_in_bot':      (1143, 'Diese Funktion wird in den Befehlen dieses Bots nicht verwendet'),
    'callout_note':         (1144, 'Hinweis'),
    'callout_limit':        (1145, 'Grenze'),
    'callout_important':    (1146, 'Wichtig!'),
    'callout_question':     (1147, 'Was ist das?'),
    'filter_all':           (1148, 'Alle'),
    'filter_command':       (1149, 'Befehl'),
    'filter_event':         (1150, 'Ereignis'),

    # ── variables_view ────────────────────────────────────────
    'variables_slash':      (1151, 'Variablen /'),
    'scoped_vars':          (1152, 'Werte pro Benutzer'),
    'value_label':          (1153, 'Wert'),
    'var_name_hint':        (1154, 'variable_name'),
    'var_value_hint':       (1155, 'variable_value'),
    'info_var':             (1156, 'Variableninfo'),
    'invalid_json':         (1157, 'Ungültiges JSON'),
    'json_must_be_object':  (1158, 'Der oberste Wert muss ein JSON-Objekt sein ({"userID": "value"}).'),

    # ── App Updater ───────────────────────────────────────────
    'app_update_title':           (1159, 'Update verfügbar'),
    'app_update_new_version':     (1160, 'Neue Version'),
    'app_update_current_version': (1161, 'Aktuell'),
    'app_update_no_changelog':    (1162, 'Kein Änderungsprotokoll für dieses Update verfügbar.'),
    'app_update_later':           (1163, 'Später'),
    'app_update_now':             (1164, 'Jetzt aktualisieren'),
    'app_update_downloading':     (1165, 'Wird heruntergeladen'),
    'app_update_done':            (1166, 'Download abgeschlossen ✓'),
    'app_update_failed':          (1167, 'Download fehlgeschlagen'),
    'app_update_open_installer':  (1168, 'Installer öffnen'),
    'app_update_installer_opened':(1169, 'Installer geöffnet. Schließen Sie die Installation ab und öffnen Sie die App erneut.'),
    'app_update_open_failed':     (1170, 'Installer konnte nicht geöffnet werden'),

    # ── Wiki-Filter (erweitert) ────────────────────────────
    'filter_variable':      (1171, 'Variablen'),
    'filter_discord':       (1172, 'Discord'),
    'filter_time':          (1173, 'Zeit'),
    'filter_other':         (1174, 'Andere'),

    # ── Status-Bot-Ansicht ────────────────────────────────────
    'status_bot_section':   (1175, 'Bot-Status'),
    'status_bot_desc':      (1176, "Konfigurieren Sie die Präsenz Ihres Bots und rotierende Statusmeldungen"),
    'open_status_bot':      (1177, 'Status verwalten'),
    'status_bot_title':     (1178, 'Bot-Status'),
    'sv_status_label':      (1179, 'Status'),
    'sv_loop_time_label':   (1180, 'Rotationszeit'),
    'sv_loop_time_seconds': (1181, 'Sekunden'),
    'sv_loop_time_hint':    (1182, 'Nur ganze Zahlen, mindestens 12 Sekunden'),
    'sv_activate_presence': (1183, 'Bot-Präsenz wird aktiviert'),
    'sv_status_entries':    (1184, 'Statuseinträge'),
    'sv_add_entry':         (1185, 'Neuen Eintrag hinzufügen'),
    'sv_entry_details_ph':  (1186, 'Statusdetails'),
    'sv_status_online':     (1187, 'Online'),
    'sv_status_idle':       (1188, 'Abwesend'),
    'sv_status_dnd':        (1189, 'Bitte nicht stören'),
    'sv_status_invisible':  (1190, 'Unsichtbar'),
    'sv_create_edit_title': (1191, 'Statuseintrag erstellen oder bearbeiten'),
    'sv_status_data':       (1192, 'Statusdaten'),
    'sv_prefix_status':     (1193, 'Statuspräfix'),
    'sv_status_field':      (1194, 'Status'),
    'sv_status_details':    (1195, 'Statusdetails'),
    'sv_prefix_hint':       (1196, 'z. B. Spielt'),
    'sv_status_hint':       (1197, 'Kurzer Statustext'),
    'sv_details_hint':      (1198, 'Zusätzliche Details, die unter dem Status angezeigt werden'),
    'sv_preview':           (1199, 'Vorschau'),
    'sv_name_bot':          (1200, 'Bot-Name'),
    'sv_app_badge':         (1201, 'APP'),
    'sv_save_entry':        (1202, 'Eintrag speichern'),
    'sv_back':              (1203, 'Zurück'),
    'sv_no_entries':        (1204, 'Noch keine Statuseinträge.'),
    'sv_unit_second':       (1205, 'Sekunde'),
    'sv_unit_minute':       (1206, 'Minute'),
    'sv_unit_hour':         (1207, 'Stunde'),
    'sv_unit_day':          (1208, 'Tag'),
    'sv_loop_time_integer_error': (1209, 'Nur ganze Zahlen — keine Dezimalstellen oder Symbole'),
    'sv_loop_time_min_error':     (1210, 'Die Rotationszeit darf nicht weniger als 12 Sekunden betragen'),
    'sv_activity_type':      (1211, 'Aktivitätstyp'),
    'sv_activity_playing':   (1212, 'Spielt'),
    'sv_activity_streaming': (1213, 'Streamt'),
    'sv_activity_listening': (1214, 'Hört'),
    'sv_activity_watching':  (1215, 'Schaut'),
    'sv_activity_competing': (1216, 'Tritt an bei'),
    'sv_stream_url':          (1217, 'Stream-URL'),
    'sv_stream_url_hint':     (1218, 'https://twitch.tv/... oder https://youtube.com/...'),
    'sv_stream_url_required': (1219, 'Für den Streaming-Status ist eine Stream-URL erforderlich'),
    'sv_stream_url_invalid':  (1220, 'Nur Twitch- oder YouTube-Links sind erlaubt'),
    'sv_help_note_title':     (1229, 'Hinweise'),
    'sv_help_note_body':      (1230, "Es kann einen Moment dauern, bis Änderungen aktiv werden. Das Hinzufügen, Bearbeiten oder "
                                      "Löschen eines Status – und das Ein- oder Ausschalten der Präsenz – während der Bot läuft, "
                                      "wird nicht sofort angewendet. Der Bot durchläuft zuerst die aktuelle Liste, daher kann es "
                                      "eine Weile dauern, bis Ihre Änderung angezeigt wird."),

    # ── Bot erstellen — Aus Backup importieren ────────────────────────────
    'import_zip_btn':         (1221, 'Aus Backup wiederherstellen'),
    'import_zip_disabled_hint': (1222, 'Legen Sie zuerst den Bot-Namen und ein gültiges Token fest'),
    'import_zip_selected':    (1223, 'Backup ausgewählt: {file_name}'),
    'import_zip_clear':       (1224, 'Entfernen'),
    'import_zip_invalid':     (1225, 'Dies scheint keine Bot-Backup-Datei zu sein'),
    'import_zip_pick_title':  (1226, 'Backup-ZIP auswählen'),
    'import_zip_applied':     (1227, 'Bot erstellt und Backup wiederhergestellt!'),
    'import_zip_failed':      (1228, 'Der Bot wurde erstellt, aber das Wiederherstellen des Backups ist fehlgeschlagen'),

    # ── Speicherrückmeldung ───────────────────────────────────────────────
    'saved_successfully':     (1231, 'Erfolgreich gespeichert'),

    # ── Mobile Warnung ───────────────────────────────────────────────────
    'mobile_warn_title':      (1232, 'Hinweis zum Hintergrundbetrieb'),
    'mobile_warn_body':       (1233, 'Der Betrieb von Bots auf mobilen Systemen (nur Android) unterliegt strengen Hintergrundbeschränkungen.\n\n• Im besten Fall kann der Bot nur bis zu 6 Stunden im Hintergrund laufen.\n• Sie müssen die Akku-Optimierung in den Geräteeinstellungen deaktivieren (auf "Uneingeschränkt" setzen).\n• Einige Geräte können den Bot sofort pausieren, wenn er minimiert wird.\n\nDas Ausführen der Bots auf Hosting/Server/VPS oder Ähnlichem wird noch nicht unterstützt.'),

    # ── Warnung zur Syntax des Befehlseditors ────────────────────────────
    'syntax_warn_banner':     (1234, 'Der Farbmodus ist aktiv. Deaktivieren Sie den Farbmodus bei großen Dateien (>2000 Zeichen), um Geräteverzögerungen zu vermeiden.'),
    'syntax_limit_refusal':   (1235, 'Farbmodus kann nicht aktiviert werden: Der Text überschreitet das 2000-Zeichen-Limit zum Schutz der Leistung.'),
    'syntax_color_label':     (1236, 'Farbe'),

    # ── Gesamtzahlen ─────────────────────────────────────────────────────
    'total_bots_count':       (1237, 'Gesamtzahl Ihrer Bots: {count}'),
    'total_vars_count':       (1238, 'Gesamtzahl der Variablen: {count}'),
    'total_cmds_count':       (1239, 'Gesamtzahl der Befehle: {count}'),
    'total_wiki_count':       (1240, 'Ergebnisse: {count}'),

    # ── Wiki-Filterblatt (erweitert) ─────────────────────────────────────
    'filter_title':          (1241, 'Kategorien'),
    'reset':                 (1242, 'Zurücksetzen'),
    'close':                 (1243, 'Schließen'),
    'done':                  (1244, 'Fertig'),
    'clear_search':          (1245, 'Suche löschen'),
    'filter_tooltip':        (1246, 'Filter'),
    'no_categories':         (1247, 'Noch keine Kategorien'),
    'verify_token':          (1248, 'Token verifizieren'),
    'verifying':             (1249, 'Wird verifiziert...'),
    'token_valid':           (1250, 'Verbindung erfolgreich! Token ist gültig.'),
    'token_invalid':         (1251, 'Ungültiger Token oder Verbindung fehlgeschlagen.'),
}