# -*- coding: utf-8 -*-
# main_app/langs/fr.py

FRENCH_DICT = {
    # ── Interface principale ──────────────────────────────────
    'main_title':          (1001, 'FDSB'),
    'no_bots_hint':        (1002, 'Aucun bot trouvé. Cliquez sur "Nouveau bot" pour en créer un.'),
    'new_bot':             (1003, 'Nouveau bot'),
    'discord':             (1004, 'Discord'),
    'github':              (1005, 'GitHub'),

    # ── Fenêtre de création de bot ────────────────────────────
    'name_label':          (1006, 'Nom'),
    'token_label':         (1007, 'Jeton (Token)'),
    'name_hint':           (1008, 'Entrez le nom du bot'),
    'token_hint':          (1009, 'Entrez le jeton du bot'),
    'make':                (1010, 'Créer'),
    'image_label':         (1011, 'Image'),
    'ok':                  (1012, 'OK'),
    'token_required':      (1013, 'Le jeton est requis'),
    'name_taken':          (1014, 'Nom déjà pris\nChoisissez un autre nom'),

    # ── Tableau de bord du bot ────────────────────────────────
    'state_server':        (1015, 'État du serveur'),
    'online':              (1016, 'En ligne'),
    'offline':             (1017, 'Hors ligne'),
    'start':               (1018, 'Démarrer'),
    'stop':                (1019, 'Arrêter'),
    'whats_new':           (1020, 'Quoi de neuf'),
    'no_updates':          (1021, 'Aucune mise à jour disponible.'),
    'no_file':             (1022, 'Fichier de mises à jour introuvable.'),
    'read_error':          (1023, 'Impossible de lire le fichier.'),
    'invite_bot':          (1024, 'Inviter le bot'),
    'back':                (1025, 'Retour'),
    'main_tab':            (1026, 'Principal'),
    'commands_tab':        (1027, 'Commandes'),
    'variables':           (1028, 'Variables'),
    'settings':            (1029, 'Paramètres'),
    'avatar_none':         (1030, 'Sans avatar'),
    'tab_main':            (1117, 'Principal'),
    'tab_commands':        (1118, 'Commandes'),
    'tab_variables':       (1119, 'Variables'),
    'tab_settings':        (1120, 'Paramètres'),

    # ── Paramètres ────────────────────────────────────────────
    'general_section':     (1031, 'Général'),
    'design_section':      (1032, 'Conception'),
    'info_section':        (1033, 'Informations'),
    'name_project':        (1034, 'Nom du projet'),
    'token_field':         (1035, 'Jeton du bot'),
    'bot_name_hint':       (1036, 'Nom du bot'),
    'bot_token_hint':      (1037, 'Jeton du bot'),
    'save':                (1038, 'Enregistrer'),
    'language':            (1039, 'Langue'),
    'wiki':                (1040, 'Wiki'),
    'link':                (1041, '(Lien)'),
    'restart_notice':      (1042, 'Redémarrage en cours...'),

    # ── Exporter les données ──────────────────────────────────
    'export_section':      (1043, 'Exporter les données'),
    'export_desc':         (1044, 'Exporter les commandes et variables en fichier ZIP'),
    'export_zip':          (1045, 'Exporter en ZIP'),
    'no_bot_selected':     (1046, 'Aucun bot sélectionné !'),
    'folders_not_found':   (1047, 'Dossiers introuvables !'),
    'export_failed':       (1048, 'Échec de l\'exportation !'),
    'export_success':      (1232, 'Exporté avec succès !'),

    # ── Zone de danger / Suppression ──────────────────────────
    'danger_zone':         (1049, 'Zone de danger'),
    'delete_bot_perm':     (1050, 'Supprimer ce bot définitivement'),
    'captcha_enter':       (1051, 'Entrez 3 chiffres'),
    'captcha_hint':        (1052, 'Entrez les 3 chiffres ci-dessus'),
    'confirm_delete':      (1053, 'Confirmer la suppression'),
    'captcha_wrong':       (1054, 'Code incorrect — Réessayez'),

    # ── Noms des thèmes ───────────────────────────────────────
    'system_wh':           (1055, 'Système (Clair)'),
    'system_da':           (1056, 'Système (Sombre)'),
    'blue_sky':            (1057, 'Bleu - Ciel'),
    'yellow_bile':         (1058, 'Jaune - Or'),
    'v2_dark':             (1059, 'Or Sombre'),

    # ── commands_view ─────────────────────────────────────────
    'commands_slash':      (1060, 'Commandes /'),
    'info_command':        (1061, 'Infos sur la commande'),
    'command_editor':      (1062, 'Éditeur de commande'),
    'total_lines':         (1063, 'Lignes'),
    'total_text':          (1064, 'Caractères'),
    'fdscript_hint':       (1065, '# Code FDScript ici...'),
    'prefix_label':        (1066, 'Préfixe'),
    'prefix_hint':         (1067, 'Exemple : !cmd'),
    'search':              (1068, 'Rechercher'),
    'commands':            (1069, 'Commandes'),
    'no_cmds_hint':        (1070, 'Aucune commande. Cliquez sur + pour en créer une.'),
    'del':                 (1071, 'Supprimer'),
    'name_required':       (1072, 'Le nom est requis'),
    'delete_q':            (1073, 'Supprimer ?'),
    'delete_confirm':      (1074, 'Êtes-vous sûr de vouloir supprimer "{item_name}" ?\nCette action est irréversible.'),
    'dest_event':          (1075, 'Événement'),
    'dest_cmd':            (1076, 'Commande'),
    'commands_label':      (1077, 'Entrez le nom de la commande'),
    'unsaved_title':       (1113, 'Modifications non enregistrées'),
    'unsaved_body':        (1114, 'Il y a des modifications non enregistrées. Voulez-vous les enregistrer avant de quitter ?'),
    'discard':             (1115, 'Ignorer'),

    # ── Anciennes clés ────────────────────────────────────────
    'create_file':         (1116, 'Créer un nouveau fichier'),
    'bot_token':           (1078, 'Jeton du bot'),
    'start_server':        (1079, 'Démarrer le serveur'),
    'stop_server':         (1080, 'Arrêter le serveur'),
    'files_list':          (1081, 'Liste des fichiers'),
    'run':                 (1082, 'Exécuter'),
    'file_name':           (1083, 'Nom du fichier'),
    'file_content':        (1084, 'Contenu du fichier'),
    'variable_name':       (1085, 'Nom de la variable'),
    'variable_value':      (1086, 'Valeur de la variable'),
    'add_variable':        (1087, 'Ajouter une variable'),
    'no_files':            (1088, 'Aucun fichier'),
    'no_variables':        (1089, 'Aucune variable'),
    'enter_token':         (1090, 'Entrez le jeton du bot'),
    'server_status':       (1091, 'État du serveur'),
    'running':             (1092, 'En cours d\'exécution'),
    'stopped':             (1093, 'Arrêté'),
    'edit':                (1094, 'Modifier'),
    'delete':              (1095, 'Supprimer'),
    'new_file':            (1096, 'Nouveau fichier'),
    'arabic':              (1097, 'Arabe'),
    'english':             (1098, 'Anglais'),
    'confirm':             (1099, 'Confirmer'),
    'cancel':              (1100, 'Annuler'),
    'success':             (1101, 'Succès'),
    'error':               (1102, 'Erreur'),
    'file_saved':          (1103, 'Fichier enregistré'),
    'variable_added':      (1104, 'Variable ajoutée'),
    'enter_file_name':     (1105, 'Entrez le nom du fichier'),
    'enter_variable_name': (1106, 'Entrez le nom de la variable'),
    'file_prefix':         (1107, 'Préfixe du fichier'),
    'enter_prefix':        (1108, 'Entrez le préfixe'),
    'prefix':              (1109, 'Préfixe'),
    'edit_prefix':         (1110, 'Modifier le préfixe'),
    'prefix_updated':      (1111, 'Préfixe mis à jour'),
    'toggle_language':     (1112, 'English'),

    # ── Wiki ─────────────────────────────────────────────────
    'tab_wiki':             (1121, 'Wiki'),
    'search_hint':          (1122, 'Rechercher une fonction...'),
    'check_updates':        (1123, 'Vérifier les mises à jour'),
    'checking':             (1124, 'Vérification...'),
    'downloading':          (1125, 'Téléchargement du wiki...'),
    'up_to_date':           (1126, 'Wiki à jour (v{v})'),
    'update_available':     (1127, 'Nouvelle mise à jour disponible (v{v})'),
    'update_failed':        (1128, 'Échec de la vérification des mises à jour'),
    'no_cache':             (1129, 'Aucune donnée locale. Appuyez sur "Vérifier les mises à jour".'),
    'no_results':           (1130, 'Aucun résultat'),
    'function_info':        (1131, 'Infos sur la fonction'),
    'no_details':           (1132, 'Aucun détail disponible'),
    'open_dashboard':       (1133, 'Ouvrir le tableau de bord'),
    'copy_syntax':          (1134, 'Copier'),
    'copied':               (1135, 'Copié !'),
    'syntax':               (1136, 'Syntaxe'),
    'parameters':           (1137, 'Paramètres'),
    'example':              (1138, 'Exemple'),
    'notes':                (1139, 'Notes'),
    'warnings':             (1140, 'Avertissements'),
    'required':             (1141, 'Requis'),
    'optional':             (1142, 'Optionnel'),
    'not_used_in_bot':      (1143, "Cette fonction n'est pas utilisée dans les commandes de ce bot"),
    'callout_note':         (1144, 'Note'),
    'callout_limit':        (1145, 'Limite'),
    'callout_important':    (1146, 'Important !'),
    'callout_question':     (1147, 'Qu\'est-ce que c\'est ?'),
    'filter_all':           (1148, 'Tout'),
    'filter_command':       (1149, 'Commande'),
    'filter_event':         (1150, 'Événement'),

    # ── variables_view ────────────────────────────────────────
    'variables_slash':      (1151, 'Variables /'),
    'scoped_vars':          (1152, 'Valeurs par utilisateur'),
    'value_label':          (1153, 'Valeur'),
    'var_name_hint':        (1154, 'variable_name'),
    'var_value_hint':       (1155, 'variable_value'),
    'info_var':             (1156, 'Info variable'),
    'invalid_json':         (1157, 'JSON invalide'),
    'json_must_be_object':  (1158, 'La valeur de niveau supérieur doit être un objet JSON ({"userID": "value"}).'),

    # ── Mise à jour de l'application ───────────────
    'app_update_title':          (1159, 'Mise à jour disponible'),
    'app_update_new_version':    (1160, 'Nouvelle version'),
    'app_update_current_version':(1161, 'Actuelle'),
    'app_update_no_changelog':   (1162, 'Aucun journal de modifications disponible pour cette mise à jour.'),
    'app_update_later':          (1163, 'Plus tard'),
    'app_update_now':            (1164, 'Mettre à jour maintenant'),
    'app_update_downloading':    (1165, 'Téléchargement en cours'),
    'app_update_done':           (1166, 'Téléchargement terminé ✓'),
    'app_update_failed':         (1167, 'Échec du téléchargement'),
    'app_update_open_installer': (1168, 'Ouvrir l\'installateur'),
    'app_update_installer_opened':(1169, 'Installateur ouvert. Terminez l\'installation, puis rouvrez l\'application.'),
    'app_update_open_failed':    (1170, 'Impossible d\'ouvrir le fichier de l\'installateur'),

    # ── Filtres wiki (étendus) ─────────────────────────────
    'filter_variable':      (1171, 'Variables'),
    'filter_discord':       (1172, 'Discord'),
    'filter_time':          (1173, 'Temps'),
    'filter_other':         (1174, 'Autre'),

    # ── Vue Statut du bot ────────────────────────────────────
    'status_bot_section':   (1175, 'Statut du bot'),
    'status_bot_desc':      (1176, "Configurez la présence de votre bot et ses messages de statut rotatifs"),
    'open_status_bot':      (1177, 'Gérer le statut'),
    'status_bot_title':     (1178, 'Statut du bot'),
    'sv_status_label':      (1179, 'Statut'),
    'sv_loop_time_label':   (1180, 'Durée de rotation'),
    'sv_loop_time_seconds': (1181, 'Secondes'),
    'sv_loop_time_hint':    (1182, 'Nombres entiers uniquement, minimum 12 secondes'),
    'sv_activate_presence': (1183, 'Activation de la présence du bot'),
    'sv_status_entries':    (1184, 'Entrées de statut'),
    'sv_add_entry':         (1185, 'Ajouter une nouvelle entrée'),
    'sv_entry_details_ph':  (1186, 'Détails du statut'),
    'sv_status_online':     (1187, 'En ligne'),
    'sv_status_idle':       (1188, 'Inactif'),
    'sv_status_dnd':        (1189, 'Ne pas déranger'),
    'sv_status_invisible':  (1190, 'Invisible'),
    'sv_create_edit_title': (1191, 'Créer ou modifier une entrée de statut'),
    'sv_status_data':       (1192, 'Données du statut'),
    'sv_prefix_status':     (1193, 'Préfixe du statut'),
    'sv_status_field':      (1194, 'Statut'),
    'sv_status_details':    (1195, 'Détails du statut'),
    'sv_prefix_hint':       (1196, 'ex. Joue à'),
    'sv_status_hint':       (1197, 'Texte de statut court'),
    'sv_details_hint':      (1198, 'Détails supplémentaires affichés sous le statut'),
    'sv_preview':           (1199, 'Aperçu'),
    'sv_name_bot':          (1200, 'Nom du bot'),
    'sv_app_badge':         (1201, 'APP'),
    'sv_save_entry':        (1202, "Enregistrer l'entrée"),
    'sv_back':              (1203, 'Retour'),
    'sv_no_entries':        (1204, 'Aucune entrée de statut pour le moment.'),
    'sv_unit_second':       (1205, 'Seconde'),
    'sv_unit_minute':       (1206, 'Minute'),
    'sv_unit_hour':         (1207, 'Heure'),
    'sv_unit_day':          (1208, 'Jour'),
    'sv_loop_time_integer_error': (1209, 'Nombres entiers uniquement — pas de décimales ni de symboles'),
    'sv_loop_time_min_error':     (1210, 'La durée de rotation ne peut pas être inférieure à 12 secondes'),
    'sv_activity_type':      (1211, "Type d'activité"),
    'sv_activity_playing':   (1212, 'Joue à'),
    'sv_activity_streaming': (1213, 'Streame'),
    'sv_activity_listening': (1214, 'Écoute'),
    'sv_activity_watching':  (1215, 'Regarde'),
    'sv_activity_competing': (1216, 'Participe à'),
    'sv_stream_url':          (1217, 'URL du stream'),
    'sv_stream_url_hint':     (1218, 'https://twitch.tv/... ou https://youtube.com/...'),
    'sv_stream_url_required': (1219, 'Une URL de stream est requise pour le statut Streaming'),
    'sv_stream_url_invalid':  (1220, 'Seuls les liens Twitch ou YouTube sont autorisés'),
    'sv_help_note_title':     (1229, 'Notes'),
    'sv_help_note_body':      (1230, "Les modifications prennent un moment avant de prendre effet. Ajouter, modifier ou "
                                      "supprimer un statut — et activer ou désactiver la présence — pendant que le bot "
                                      "fonctionne ne s'applique pas instantanément. Le bot termine d'abord la rotation de "
                                      "la liste actuelle, donc cela peut prendre un certain temps avant que votre mise à "
                                      "jour n'apparaisse."),

    # ── Créer un bot — Importer depuis une sauvegarde ──────────────────────
    'import_zip_btn':         (1221, 'Restaurer depuis une sauvegarde'),
    'import_zip_disabled_hint': (1222, "Définissez d'abord le nom du bot et un jeton valide"),
    'import_zip_selected':    (1223, 'Sauvegarde sélectionnée : {file_name}'),
    'import_zip_clear':       (1224, 'Retirer'),
    'import_zip_invalid':     (1225, "Cela ne ressemble pas à un fichier de sauvegarde de bot"),
    'import_zip_pick_title':  (1226, 'Choisir un ZIP de sauvegarde'),
    'import_zip_applied':     (1227, 'Bot créé et sauvegarde restaurée !'),
    'import_zip_failed':      (1228, "Le bot a été créé, mais la restauration de la sauvegarde a échoué"),

    # ── Retour de sauvegarde ──────────────────────────────────────────────
    'saved_successfully':     (1231, 'Enregistré avec succès'),

    # ── Avertissement Mobile ──────────────────────────────────────────────
    'mobile_warn_title':      (1232, 'Avis d\'exécution en arrière-plan'),
    'mobile_warn_body':       (1233, 'Exécuter des bots sur des systèmes mobiles (Android uniquement) est soumis à des limites strictes en arrière-plan.\n\n• Dans le meilleur des cas, le bot peut fonctionner en arrière-plan pendant 6 heures maximum.\n• Vous devez désactiver l\'optimisation de la batterie (régler sur "Non restreint") dans les paramètres de votre appareil.\n• Certains appareils peuvent suspendre le bot immédiatement lorsqu\'il est réduit.\n\nConcernant l\'exécution des bots sur un hébergeur/serveur/VPS ou similaire, ce n\'est pas encore pris en charge.'),

    # ── Avertissement de syntaxe de l\'éditeur de commandes ────────────────
    'syntax_warn_banner':     (1234, 'Le mode couleur est actif. Pour les fichiers volumineux (>2000 caractères), désactivez le mode couleur pour éviter les ralentissements.'),
    'syntax_limit_refusal':   (1235, 'Impossible d\'activer le mode couleur : le texte dépasse la limite de 2000 caractères pour protéger les performances.'),
    'syntax_color_label':     (1236, 'Couleur'),

    # ── Totaux ────────────────────────────────────────────────────────────
    'total_bots_count':       (1237, 'Total de bots en votre possession : {count}'),
    'total_vars_count':       (1238, 'Total de variables : {count}'),
    'total_cmds_count':       (1239, 'Total de commandes : {count}'),
    'total_wiki_count':       (1240, 'Résultats : {count}'),

    # ── Feuille de filtres wiki (étendue) ─────────────────────────────────
    'filter_title':          (1241, 'Catégories'),
    'reset':                 (1242, 'Réinitialiser'),
    'close':                 (1243, 'Fermer'),
    'done':                  (1244, 'Terminé'),
    'clear_search':          (1245, 'Effacer la recherche'),
    'filter_tooltip':        (1246, 'Filtrer'),
    'no_categories':         (1247, 'Aucune catégorie pour le moment'),
    'verify_token':          (1248, 'Vérifier le jeton'),
    'verifying':             (1249, 'Vérification...'),
    'token_valid':           (1250, 'Connexion réussie ! Le jeton est valide.'),
    'token_invalid':         (1251, 'Jeton invalide ou connexion échouée.'),
}
