# -*- coding: utf-8 -*-
# main_app/langs/pl.py

POLISH_DICT = {
    # ── Main Interface ────────────────────────────────────────
    'main_title':          (1001, 'FDSB'),
    'no_bots_hint':        (1002, 'Nie znaleziono botów. Kliknij "Nowy bot", aby go utworzyć.'),
    'new_bot':             (1003, 'Nowy bot'),
    'discord':             (1004, 'Discord'),
    'github':              (1005, 'GitHub'),

    # ── Create Bot Window ─────────────────────────────────────
    'name_label':          (1006, 'Nazwa'),
    'token_label':         (1007, 'Token'),
    'name_hint':           (1008, 'Wprowadź nazwę bota'),
    'token_hint':          (1009, 'Wprowadź token bota'),
    'make':                (1010, 'Utwórz'),
    'image_label':         (1011, 'Obraz'),
    'ok':                  (1012, 'OK'),
    'token_required':      (1013, 'Token jest wymagany'),
    'name_taken':          (1014, 'Nazwa jest już zajęta\nWybierz inną nazwę'),

    # ── Bot Dashboard ─────────────────────────────────────────
    'state_server':        (1015, 'Status serwera'),
    'online':              (1016, 'Online'),
    'offline':             (1017, 'Offline'),
    'start':               (1018, 'Uruchom'),
    'stop':                (1019, 'Zatrzymaj'),
    'whats_new':           (1020, 'Co nowego'),
    'no_updates':          (1021, 'Brak dostępnych aktualizacji.'),
    'no_file':             (1022, 'Nie znaleziono pliku aktualizacji.'),
    'read_error':          (1023, 'Nie można odczytać pliku.'),
    'invite_bot':          (1024, 'Zaproś bota'),
    'back':                (1025, 'Wstecz'),
    'main_tab':            (1026, 'Główne'),
    'commands_tab':        (1027, 'Komendy'),
    'variables':           (1028, 'Zmienne'),
    'settings':            (1029, 'Ustawienia'),
    'avatar_none':         (1030, 'Brak awatara'),
    'tab_main':            (1117, 'Główne'),
    'tab_commands':        (1118, 'Komendy'),
    'tab_variables':       (1119, 'Zmienne'),
    'tab_settings':        (1120, 'Ustawienia'),

    # ── Settings ──────────────────────────────────────────────
    'general_section':     (1031, 'Ogólne'),
    'design_section':      (1032, 'Wygląd'),
    'info_section':        (1033, 'Informacje'),
    'name_project':        (1034, 'Nazwa projektu'),
    'token_field':         (1035, 'Token bota'),
    'bot_name_hint':       (1036, 'Nazwa bota'),
    'bot_token_hint':      (1037, 'Token bota'),
    'save':                (1038, 'Zapisz'),
    'language':            (1039, 'Język'),
    'wiki':                (1040, 'Wiki'),
    'link':                (1041, '(Link)'),
    'restart_notice':      (1042, 'Ponowne uruchamianie...'),

    # ── Export Data ───────────────────────────────────────────
    'export_section':      (1043, 'Eksportuj dane'),
    'export_desc':         (1044, 'Eksportuj komendy i zmienne jako plik ZIP'),
    'export_zip':          (1045, 'Eksportuj ZIP'),
    'no_bot_selected':     (1046, 'Nie wybrano bota!'),
    'folders_not_found':   (1047, 'Nie znaleziono folderów!'),
    'export_failed':       (1048, 'Eksport nie powiódł się!'),
    'export_success':      (1232, 'Wyeksportowano pomyślnie!'),

    # ── Danger Zone / Delete ──────────────────────────────────
    'danger_zone':         (1049, 'Strefa niebezpieczna'),
    'delete_bot_perm':     (1050, 'Usuń tego bota trwale'),
    'captcha_enter':       (1051, 'Wprowadź 3 cyfry'),
    'captcha_hint':        (1052, 'Wprowadź 3 cyfry pokazane powyżej'),
    'confirm_delete':      (1053, 'Potwierdź usunięcie'),
    'captcha_wrong':       (1054, 'Błędny kod — Spróbuj ponownie'),

    # ── Themes Names ──────────────────────────────────────────
    'system_wh':           (1055, 'Systemowy (Jasny)'),
    'system_da':           (1056, 'Systemowy (Ciemny)'),
    'blue_sky':            (1057, 'Niebieski - Niebo'),
    'yellow_bile':         (1058, 'Żółty - Złoty'),
    'v2_dark':             (1059, 'Ciemne złoto'),

    # ── commands_view ─────────────────────────────────────────
    'commands_slash':      (1060, 'Komendy /'),
    'info_command':        (1061, 'Informacje o komendzie'),
    'command_editor':      (1062, 'Edytor komend'),
    'total_lines':         (1063, 'Linie'),
    'total_text':          (1064, 'Znaki'),
    'fdscript_hint':       (1065, '# Tutaj kod FDScript...'),
    'prefix_label':        (1066, 'Prefiks'),
    'prefix_hint':         (1067, 'Przykład: !cmd'),
    'search':              (1068, 'Szukaj'),
    'commands':            (1069, 'Komendy'),
    'no_cmds_hint':        (1070, 'Nie znaleziono komend. Kliknij +, aby utworzyć.'),
    'del':                 (1071, 'Usuń'),
    'name_required':       (1072, 'Nazwa jest wymagana'),
    'delete_q':            (1073, 'Usunąć?'),
    'delete_confirm':      (1074, 'Czy na pewno chcesz usunąć "{item_name}"?\nTej operacji nie można cofnąć.'),
    'dest_event':          (1075, 'Zdarzenie'),
    'dest_cmd':            (1076, 'Komenda'),
    'commands_label':      (1077, 'Wprowadź nazwę komendy'),
    'unsaved_title':       (1113, 'Niezapisane zmiany'),
    'unsaved_body':        (1114, 'Istnieją niezapisane zmiany. Czy chcesz je zapisać przed wyjściem?'),
    'discard':             (1115, 'Odrzuć'),

    # ── wiki_view ─────────────────────────────────────────────
    'tab_wiki':            (1121, 'Wiki'),
    'search_hint':         (1122, 'Szukaj funkcji...'),
    'check_updates':       (1123, 'Sprawdź aktualizacje'),
    'checking':            (1124, 'Sprawdzanie...'),
    'downloading':         (1125, 'Pobieranie wiki...'),
    'up_to_date':          (1126, 'Wiki jest aktualna (v{v})'),
    'update_available':    (1127, 'Dostępna jest nowa aktualizacja (v{v})'),
    'update_failed':       (1128, 'Nie udało się sprawdzić aktualizacji'),
    'no_cache':            (1129, 'Brak danych lokalnych. Naciśnij "Sprawdź aktualizacje".'),
    'no_results':          (1130, 'Brak wyników'),
    'function_info':       (1131, 'Informacje o funkcji'),
    'no_details':          (1132, 'Brak dostępnych szczegółów'),
    'open_dashboard':      (1133, 'Otwórz pulpit'),
    'copy_syntax':         (1134, 'Kopiuj'),
    'copied':              (1135, 'Skopiowano!'),
    'syntax':              (1136, 'Składnia'),
    'parameters':          (1137, 'Parametry'),
    'example':             (1138, 'Przykład'),
    'notes':               (1139, 'Uwagi'),
    'warnings':            (1140, 'Ostrzeżenia'),
    'required':            (1141, 'Wymagane'),
    'optional':            (1142, 'Opcjonalne'),
    'not_used_in_bot':     (1143, 'Ta funkcja nie jest używana w komendach tego bota'),

    # ── Old Keys ──────────────────────────────────────────────
    'create_file':         (1116, 'Utwórz nowy plik'),
    'bot_token':           (1078, 'Token bota'),
    'start_server':        (1079, 'Uruchom serwer'),
    'stop_server':         (1080, 'Zatrzymaj serwer'),
    'files_list':          (1081, 'Lista plików'),
    'run':                 (1082, 'Uruchom'),
    'file_name':           (1083, 'Nazwa pliku'),
    'file_content':        (1084, 'Zawartość pliku'),
    'variable_name':       (1085, 'Nazwa zmiennej'),
    'variable_value':      (1086, 'Wartość zmiennej'),
    'add_variable':        (1087, 'Dodaj zmienną'),
    'no_files':            (1088, 'Brak plików'),
    'no_variables':        (1089, 'Brak zmiennych'),
    'enter_token':         (1090, 'Wprowadź token bota'),
    'server_status':       (1091, 'Status serwera'),
    'running':             (1092, 'Uruchomiony'),
    'stopped':             (1093, 'Zatrzymany'),
    'edit':                (1094, 'Edytuj'),
    'delete':              (1095, 'Usuń'),
    'new_file':            (1096, 'Nowy plik'),
    'arabic':              (1097, 'Arabski'),
    'english':             (1098, 'Angielski'),
    'confirm':             (1099, 'Potwierdź'),
    'cancel':              (1100, 'Anuluj'),
    'success':             (1101, 'Sukces'),
    'error':               (1102, 'Błąd'),
    'file_saved':          (1103, 'Zapisano plik'),
    'variable_added':      (1104, 'Dodano zmienną'),
    'enter_file_name':     (1105, 'Wprowadź nazwę pliku'),
    'enter_variable_name': (1106, 'Wprowadź nazwę zmiennej'),
    'file_prefix':         (1107, 'Prefiks pliku'),
    'enter_prefix':        (1108, 'Wprowadź prefiks'),
    'prefix':              (1109, 'Prefiks'),
    'edit_prefix':         (1110, 'Edytuj prefiks'),
    'prefix_updated':      (1111, 'Zaktualizowano prefiks'),
    'toggle_language':     (1112, 'Polski'), 

    # ── wiki_view filters ───────────────────────────────────
    'filter_all':          (1148, 'Wszystkie'),
    'filter_command':      (1149, 'Komenda'),
    'filter_event':        (1150, 'Zdarzenie'),

    # ── wiki_view callouts ───────────────────────────────────
    'callout_note':        (1144, 'Uwaga'),
    'callout_limit':       (1145, 'Limit'),
    'callout_important':   (1146, 'To ważne!'),
    'callout_question':    (1147, 'Co to jest?'),

    # ── variables_view ────────────────────────────────────────
    'variables_slash':     (1151, 'Zmienne /'),
    'scoped_vars':         (1152, 'Wartości indywidualne'),
    'value_label':         (1153, 'Wartość'),
    'var_name_hint':       (1154, 'nazwa_zmiennej'),
    'var_value_hint':      (1155, 'wartość_zmiennej'),
    'info_var':            (1156, 'Informacje o zmiennej'),
    'invalid_json':        (1157, 'Nieprawidłowy JSON'),
    'json_must_be_object': (1158, 'Wartość najwyższego poziomu musi być obiektem JSON ({"userID": "value"}).'),

    # ── Aktualizator aplikacji ─────────────────────
    'app_update_title':          (1159, 'Dostępna aktualizacja'),
    'app_update_new_version':    (1160, 'Nowa wersja'),
    'app_update_current_version':(1161, 'Bieżąca'),
    'app_update_no_changelog':   (1162, 'Brak dziennika zmian dla tej aktualizacji.'),
    'app_update_later':          (1163, 'Później'),
    'app_update_now':            (1164, 'Aktualizuj teraz'),
    'app_update_downloading':    (1165, 'Pobieranie'),
    'app_update_done':           (1166, 'Pobieranie zakończone ✓'),
    'app_update_failed':         (1167, 'Pobieranie nie powiodło się'),
    'app_update_open_installer': (1168, 'Otwórz instalator'),
    'app_update_installer_opened':(1169, 'Instalator otwarty. Dokończ instalację, a następnie otwórz ponownie aplikację.'),
    'app_update_open_failed':    (1170, 'Nie można otworzyć pliku instalatora'),

    # ── wiki_view filters (extended) ─────────────────────────
    'filter_variable':      (1171, 'Zmienne'),
    'filter_discord':       (1172, 'Discord'),
    'filter_time':          (1173, 'Czas'),
    'filter_other':         (1174, 'Inne'),

    # ── Widok statusu bota ────────────────────────────────────
    'status_bot_section':   (1175, 'Status bota'),
    'status_bot_desc':      (1176, 'Skonfiguruj obecność bota i zmieniające się komunikaty statusu'),
    'open_status_bot':      (1177, 'Zarządzaj statusem'),
    'status_bot_title':     (1178, 'Status bota'),
    'sv_status_label':      (1179, 'Status'),
    'sv_loop_time_label':   (1180, 'Czas rotacji'),
    'sv_loop_time_seconds': (1181, 'Sekundy'),
    'sv_loop_time_hint':    (1182, 'Tylko liczby całkowite, min. 12 sekund'),
    'sv_activate_presence': (1183, 'Aktywowanie obecności bota'),
    'sv_status_entries':    (1184, 'Wpisy statusu'),
    'sv_add_entry':         (1185, 'Dodaj nowy wpis'),
    'sv_entry_details_ph':  (1186, 'Szczegóły statusu'),
    'sv_status_online':     (1187, 'Online'),
    'sv_status_idle':       (1188, 'Bezczenny'),
    'sv_status_dnd':        (1189, 'Nie przeszkadzać'),
    'sv_status_invisible':  (1190, 'Niewidoczny'),
    'sv_create_edit_title': (1191, 'Utwórz lub edytuj wpis statusu'),
    'sv_status_data':       (1192, 'Dane statusu'),
    'sv_prefix_status':     (1193, 'Prefiks statusu'),
    'sv_status_field':      (1194, 'Status'),
    'sv_status_details':    (1195, 'Szczegóły statusu'),
    'sv_prefix_hint':       (1196, 'np. Gra w'),
    'sv_status_hint':       (1197, 'Krótki tekst statusu'),
    'sv_details_hint':      (1198, 'Dodatkowe szczegóły wyświetlane pod statusem'),
    'sv_preview':           (1199, 'Podgląd'),
    'sv_name_bot':          (1200, 'Nazwa bota'),
    'sv_app_badge':         (1201, 'APP'),
    'sv_save_entry':        (1202, 'Zapisz wpis'),
    'sv_back':              (1203, 'Wstecz'),
    'sv_no_entries':        (1204, 'Brak wpisów statusu.'),
    'sv_unit_second':       (1205, 'Sekunda'),
    'sv_unit_minute':       (1206, 'Minuta'),
    'sv_unit_hour':         (1207, 'Godzina'),
    'sv_unit_day':          (1208, 'Dzień'),
    'sv_loop_time_integer_error': (1209, 'Tylko liczby całkowite — bez miejsc dziesiętnych i symboli'),
    'sv_loop_time_min_error':     (1210, 'Czas rotacji nie może być krótszy niż 12 sekund'),
    'sv_activity_type':      (1211, 'Typ aktywności'),
    'sv_activity_playing':   (1212, 'Gra w'),
    'sv_activity_streaming': (1213, 'Streamuje'),
    'sv_activity_listening': (1214, 'Słucha'),
    'sv_activity_watching':  (1215, 'Ogląda'),
    'sv_activity_competing': (1216, 'Rywalizuje w'),
    'sv_stream_url':          (1217, 'Adres URL transmisji'),
    'sv_stream_url_hint':     (1218, 'https://twitch.tv/... lub https://youtube.com/...'),
    'sv_stream_url_required': (1219, 'Adres URL transmisji jest wymagany dla statusu transmisji'),
    'sv_stream_url_invalid':  (1220, 'Dozwolone są tylko linki Twitch lub YouTube'),
    'sv_help_note_title':     (1229, 'Uwagi'),
    'sv_help_note_body':      (1230, "Zmiany chwilę trwają, zanim zaczną obowiązywać. Dodawanie, edytowanie lub "
                                      "usuwanie statusu — oraz włączanie lub wyłączanie obecności — podczas "
                                      "działania bota nie zostanie zastosowane natychmiast. Bot najpierw kończy "
                                      "rotację bieżącej listy, więc może upłynąć chwilę, zanim Twoja aktualizacja "
                                      "się pojawi."),

    # ── Tworzenie bota — Import z kopii zapasowej ──────────────────────
    'import_zip_btn':         (1221, 'Przywróć z kopii zapasowej'),
    'import_zip_disabled_hint': (1222, 'Najpierw ustaw nazwę bota i prawidłowy token'),
    'import_zip_selected':    (1223, 'Wybrano kopię zapasową: {file_name}'),
    'import_zip_clear':       (1224, 'Usuń'),
    'import_zip_invalid':     (1225, 'To nie wygląda na plik kopii zapasowej bota'),
    'import_zip_pick_title':  (1226, 'Wybierz plik ZIP kopii zapasowej'),
    'import_zip_applied':     (1227, 'Utworzono bota i przywrócono kopię zapasową!'),
    'import_zip_failed':      (1228, 'Bot został utworzony, ale przywracanie kopii zapasowej nie powiodło się'),

    # ── Informacja o zapisie ──────────────────────────────────────────────
    'saved_successfully':     (1231, 'Pomyślnie zapisano'),

    # ── Ostrzeżenie mobilne ─────────────────────────────────────────────
    'mobile_warn_title':      (1232, 'Uwaga o działaniu w tle'),
    'mobile_warn_body':       (1233, 'Uruchamianie botów na systemach mobilnych (tylko Android) podlega ścisłym ograniczeniom działania w tle.\n\n• W najlepszym przypadku bot może działać w tle maksymalnie 6 godzin.\n• Musisz wyłączyć optymalizację baterii (ustawić na "Bez ograniczeń") w ustawieniach urządzenia.\n• Niektóre urządzenia mogą natychmiast zawiesić bota po zminimalizowaniu.\n\nJeśli chodzi o uruchamianie botów na hostingu/serwerze/VPS lub podobnym, nie jest to jeszcze obsługiwane.'),

    # ── Ostrzeżenie o składni edytora komend ────────────────────────────
    'syntax_warn_banner':     (1234, 'Tryb kolorowy jest aktywny. W przypadku dużych plików (>2000 znaków) wyłącz tryb kolorowy, aby uniknąć opóźnień urządzenia.'),
    'syntax_limit_refusal':   (1235, 'Nie można włączyć trybu kolorowego: tekst przekracza limit 2000 znaków w celu ochrony wydajności.'),
    'syntax_color_label':     (1236, 'Kolor'),

    # ── Łączne liczby ───────────────────────────────────────────────────
    'total_bots_count':       (1237, 'Łączna liczba botów, które posiadasz: {count}'),
    'total_vars_count':       (1238, 'Łączna liczba zmiennych: {count}'),
    'total_cmds_count':       (1239, 'Łączna liczba komend: {count}'),
    'total_wiki_count':       (1240, 'Wyniki: {count}'),

    # ── Arkusz filtrów wiki (rozszerzony) ───────────────────────────────
    'filter_title':          (1241, 'Kategorie'),
    'reset':                 (1242, 'Resetuj'),
    'close':                 (1243, 'Zamknij'),
    'done':                  (1244, 'Gotowe'),
    'clear_search':          (1245, 'Wyczyść wyszukiwanie'),
    'filter_tooltip':        (1246, 'Filtr'),
    'no_categories':         (1247, 'Brak kategorii'),
    'verify_token':          (1248, 'Zweryfikuj token'),
    'verifying':             (1249, 'Weryfikowanie...'),
    'token_valid':           (1250, 'Połączenie pomyślne! Token jest prawidłowy.'),
    'token_invalid':         (1251, 'Nieprawidłowy token lub nieudane połączenie.'),
}
