# -*- coding: utf-8 -*-
# main_app/langs/tr.py

TURKISH_DICT = {
    # ── Ana Arayüz ────────────────────────────────────
    'main_title':          (1001, 'FDSB'),
    'no_bots_hint':        (1002, 'Bot bulunamadı. Oluşturmak için "Yeni Bot"a tıklayın.'),
    'new_bot':             (1003, 'Yeni Bot'),
    'discord':             (1004, 'Discord'),
    'github':              (1005, 'GitHub'),

    # ── Bot Oluşturma Penceresi ────────────────────────────────
    'name_label':          (1006, 'İsim'),
    'token_label':         (1007, 'Token'),
    'name_hint':           (1008, 'Bot ismini girin'),
    'token_hint':          (1009, 'Bot tokenini girin'),
    'make':                (1010, 'Oluştur'),
    'image_label':         (1011, 'Resim'),
    'ok':                  (1012, 'Tamam'),
    'token_required':      (1013, 'Token gereklidir'),
    'name_taken':          (1014, 'İsim zaten kullanımda\nBaşka bir isim seçin'),

    # ── Bot Kontrol Paneli ─────────────────────────────────────────
    'state_server':        (1015, 'Sunucu durumu'),
    'online':              (1016, 'Çevrimiçi'),
    'offline':             (1017, 'Çevrimdışı'),
    'start':               (1018, 'Başlat'),
    'stop':                (1019, 'Durdur'),
    'whats_new':           (1020, 'Yenilikler'),
    'no_updates':          (1021, 'Güncelleme yok.'),
    'no_file':             (1022, 'Güncelleme dosyası bulunamadı.'),
    'read_error':          (1023, 'Dosya okunamadı.'),
    'invite_bot':          (1024, 'Botu davet et'),
    'back':                (1025, 'Geri'),
    'main_tab':            (1026, 'Ana Sayfa'),
    'commands_tab':        (1027, 'Komutlar'),
    'variables':           (1028, 'Değişkenler'),
    'settings':            (1029, 'Ayarlar'),
    'avatar_none':         (1030, 'Avatar yok'),
    'tab_main':            (1117, 'Ana Sayfa'),
    'tab_commands':        (1118, 'Komutlar'),
    'tab_variables':       (1119, 'Değişkenler'),
    'tab_settings':        (1120, 'Ayarlar'),

    # ── Ayarlar ─────────────────────────────────────────
    'general_section':     (1031, 'Genel'),
    'design_section':      (1032, 'Tasarım'),
    'info_section':        (1033, 'Bilgi'),
    'name_project':        (1034, 'Proje ismi'),
    'token_field':         (1035, 'Bot Tokeni'),
    'bot_name_hint':       (1036, 'Bot ismi'),
    'bot_token_hint':      (1037, 'Bot tokeni'),
    'save':                (1038, 'Kaydet'),
    'language':            (1039, 'Dil'),
    'wiki':                (1040, 'Wiki'),
    'link':                (1041, '(Bağlantı)'),
    'restart_notice':      (1042, 'Yeniden başlatılıyor...'),

    # ── Veri Dışa Aktarma ─────────────────────────────────────
    'export_section':      (1043, 'Veriyi dışa aktar'),
    'export_desc':         (1044, 'Komutları ve değişkenleri ZIP olarak dışa aktar'),
    'export_zip':          (1045, 'ZIP olarak aktar'),
    'no_bot_selected':     (1046, 'Bot seçilmedi!'),
    'folders_not_found':   (1047, 'Klasörler bulunamadı!'),
    'export_failed':       (1048, 'Dışa aktarma başarısız!'),
    'export_success':      (1232, 'Dışa aktarma başarılı!'),

    # ── Tehlike Bölgesi / Silme ────────────────────────────────
    'danger_zone':         (1049, 'Tehlike bölgesi'),
    'delete_bot_perm':     (1050, 'Bu botu kalıcı olarak sil'),
    'captcha_enter':       (1051, '3 rakam girin'),
    'captcha_hint':        (1052, 'Yukarıda gösterilen 3 rakamı girin'),
    'confirm_delete':      (1053, 'Silmeyi onayla'),
    'captcha_wrong':       (1054, 'Yanlış kod — Tekrar deneyin'),

    # ── Tema İsimleri ───────────────────────────────────────────
    'system_wh':           (1055, 'Sistem (Açık)'),
    'system_da':           (1056, 'Sistem (Koyu)'),
    'blue_sky':            (1057, 'Mavi - Gökyüzü'),
    'yellow_bile':         (1058, 'Sarı - Altın'),
    'v2_dark':             (1059, 'Koyu Altın'),

    # ── Komut Görünümü ─────────────────────────────────────────
    'commands_slash':      (1060, '/ Komutlar'),
    'info_command':        (1061, 'Komut bilgisi'),
    'command_editor':      (1062, 'Komut düzenleyici'),
    'total_lines':         (1063, 'Satır'),
    'total_text':          (1064, 'Karakter'),
    'fdscript_hint':       (1065, '# FDScript kodunu buraya yazın...'),
    'prefix_label':        (1066, 'Önek'),
    'prefix_hint':         (1067, 'Örnek: !cmd'),
    'search':              (1068, 'Ara'),
    'commands':            (1069, 'Komutlar'),
    'no_cmds_hint':        (1070, 'Komut yok. Bir tane oluşturmak için + butonuna tıklayın.'),
    'del':                 (1071, 'Sil'),
    'name_required':       (1072, 'İsim gereklidir'),
    'delete_q':            (1073, 'Silinsin mi?'),
    'delete_confirm':      (1074, '"{item_name}" ögesini silmek istediğinize emin misiniz?\nBu işlem geri alınamaz.'),
    'dest_event':          (1075, 'Olay'),
    'dest_cmd':            (1076, 'Komut'),
    'commands_label':      (1077, 'Komut ismini girin'),
    'unsaved_title':       (1113, 'Kaydedilmemiş değişiklikler'),
    'unsaved_body':        (1114, 'Kaydedilmemiş değişiklikler var. Çıkmadan önce kaydetmek ister misiniz?'),
    'discard':             (1115, 'Vazgeç'),

    # ── Eski Anahtarlar ────────────────────────────────────────
    'create_file':         (1116, 'Yeni dosya oluştur'),
    'bot_token':           (1078, 'Bot Tokeni'),
    'start_server':        (1079, 'Sunucuyu başlat'),
    'stop_server':         (1080, 'Sunucuyu durdur'),
    'files_list':          (1081, 'Dosya listesi'),
    'run':                 (1082, 'Çalıştır'),
    'file_name':           (1083, 'Dosya ismi'),
    'file_content':        (1084, 'Dosya içeriği'),
    'variable_name':       (1085, 'Değişken ismi'),
    'variable_value':      (1086, 'Değişken değeri'),
    'add_variable':        (1087, 'Değişken ekle'),
    'no_files':            (1088, 'Dosya yok'),
    'no_variables':        (1089, 'Değişken yok'),
    'enter_token':         (1090, 'Bot tokenini girin'),
    'server_status':       (1091, 'Sunucu durumu'),
    'running':             (1092, 'Çalışıyor'),
    'stopped':             (1093, 'Durduruldu'),
    'edit':                (1094, 'Düzenle'),
    'delete':              (1095, 'Sil'),
    'new_file':            (1096, 'Yeni dosya'),
    'arabic':              (1097, 'Arapça'),
    'english':             (1098, 'İngilizce'),
    'confirm':             (1099, 'Onayla'),
    'cancel':              (1100, 'İptal'),
    'success':             (1101, 'Başarılı'),
    'error':               (1102, 'Hata'),
    'file_saved':          (1103, 'Dosya kaydedildi'),
    'variable_added':      (1104, 'Değişken eklendi'),
    'enter_file_name':     (1105, 'Dosya ismini girin'),
    'enter_variable_name': (1106, 'Değişken ismini girin'),
    'file_prefix':         (1107, 'Dosya öneki'),
    'enter_prefix':        (1108, 'Önek girin'),
    'prefix':              (1109, 'Önek'),
    'edit_prefix':         (1110, 'Öneki düzenle'),
    'prefix_updated':      (1111, 'Önek güncellendi'),
    'toggle_language':     (1112, 'English'),

    # ── Wiki ─────────────────────────────────────────────────
    'tab_wiki':             (1121, 'Wiki'),
    'search_hint':          (1122, 'Fonksiyon ara...'),
    'check_updates':        (1123, 'Güncellemeleri kontrol et'),
    'checking':             (1124, 'Kontrol ediliyor...'),
    'downloading':          (1125, 'Wiki indiriliyor...'),
    'up_to_date':           (1126, 'Wiki güncel (v{v})'),
    'update_available':     (1127, 'Yeni güncelleme mevcut (v{v})'),
    'update_failed':        (1128, 'Güncelleme kontrolü başarısız'),
    'no_cache':             (1129, 'Henüz yerel veri yok. "Güncellemeleri kontrol et" e dokunun.'),
    'no_results':           (1130, 'Sonuç yok'),
    'function_info':        (1131, 'Fonksiyon bilgisi'),
    'no_details':           (1132, 'Ayrıntı mevcut değil'),
    'open_dashboard':       (1133, 'Kontrol panelini aç'),
    'copy_syntax':          (1134, 'Kopyala'),
    'copied':               (1135, 'Kopyalandı!'),
    'syntax':               (1136, 'Sözdizimi'),
    'parameters':           (1137, 'Parametreler'),
    'example':              (1138, 'Örnek'),
    'notes':                (1139, 'Notlar'),
    'warnings':             (1140, 'Uyarılar'),
    'required':             (1141, 'Gerekli'),
    'optional':             (1142, 'İsteğe bağlı'),
    'not_used_in_bot':      (1143, 'Bu fonksiyon bu botun komutlarında kullanılmıyor'),
    'callout_note':         (1144, 'Not'),
    'callout_limit':        (1145, 'Sınır'),
    'callout_important':    (1146, 'Önemli!'),
    'callout_question':     (1147, 'Bu nedir?'),
    'filter_all':           (1148, 'Tümü'),
    'filter_command':       (1149, 'Komut'),
    'filter_event':         (1150, 'Olay'),

    # ── variables_view ────────────────────────────────────────
    'variables_slash':      (1151, 'Değişkenler /'),
    'scoped_vars':          (1152, 'Kullanıcı başına değerler'),
    'value_label':          (1153, 'Değer'),
    'var_name_hint':        (1154, 'variable_name'),
    'var_value_hint':       (1155, 'variable_value'),
    'info_var':             (1156, 'Değişken bilgisi'),
    'invalid_json':         (1157, 'Geçersiz JSON'),
    'json_must_be_object':  (1158, 'Üst düzey değer bir JSON nesnesi olmalıdır ({"userID": "value"}).'),

    # ── Uygulama Güncelleyici ──────────────────────
    'app_update_title':          (1159, 'Güncelleme mevcut'),
    'app_update_new_version':    (1160, 'Yeni Sürüm'),
    'app_update_current_version':(1161, 'Mevcut'),
    'app_update_no_changelog':   (1162, 'Bu güncelleme için değişiklik günlüğü yok.'),
    'app_update_later':          (1163, 'Sonra'),
    'app_update_now':            (1164, 'Şimdi Güncelle'),
    'app_update_downloading':    (1165, 'İndiriliyor'),
    'app_update_done':           (1166, 'İndirme tamamlandı ✓'),
    'app_update_failed':         (1167, 'İndirme başarısız'),
    'app_update_open_installer': (1168, 'Kurulumu Aç'),
    'app_update_installer_opened':(1169, 'Kurulum açıldı. Kurulumu tamamlayın ve uygulamayı yeniden açın.'),
    'app_update_open_failed':    (1170, 'Kurulum dosyası açılamadı'),

    # ── wiki_view filters (extended) ─────────────────────────
    'filter_variable':      (1171, 'Değişkenler'),
    'filter_discord':       (1172, 'Discord'),
    'filter_time':          (1173, 'Zaman'),
    'filter_other':         (1174, 'Diğer'),

    # ── Bot Durumu Görünümü ──────────────────────────────────
    'status_bot_section':   (1175, 'Bot durumu'),
    'status_bot_desc':      (1176, "Botunuzun varlığını ve döngüsel durum mesajlarını yapılandırın"),
    'open_status_bot':      (1177, 'Durumu yönet'),
    'status_bot_title':     (1178, 'Bot Durumu'),
    'sv_status_label':      (1179, 'Durum'),
    'sv_loop_time_label':   (1180, 'Döngü süresi'),
    'sv_loop_time_seconds': (1181, 'Saniye'),
    'sv_loop_time_hint':    (1182, 'Yalnızca tam sayı, en az 12 saniye'),
    'sv_activate_presence': (1183, 'Bot varlığı etkinleştiriliyor'),
    'sv_status_entries':    (1184, 'Durum girdileri'),
    'sv_add_entry':         (1185, 'Yeni giriş ekle'),
    'sv_entry_details_ph':  (1186, 'Durum ayrıntıları'),
    'sv_status_online':     (1187, 'Çevrimiçi'),
    'sv_status_idle':       (1188, 'Boşta'),
    'sv_status_dnd':        (1189, 'Rahatsız Etmeyin'),
    'sv_status_invisible':  (1190, 'Görünmez'),
    'sv_create_edit_title': (1191, 'Durum girişi oluşturun veya düzenleyin'),
    'sv_status_data':       (1192, 'Durum verileri'),
    'sv_prefix_status':     (1193, 'Durum öneki'),
    'sv_status_field':      (1194, 'Durum'),
    'sv_status_details':    (1195, 'Durum ayrıntıları'),
    'sv_prefix_hint':       (1196, 'örn. Oynuyor'),
    'sv_status_hint':       (1197, 'Kısa durum metni'),
    'sv_details_hint':      (1198, "Durumun altında gösterilen ek ayrıntılar"),
    'sv_preview':           (1199, 'Önizleme'),
    'sv_name_bot':          (1200, 'Bot adı'),
    'sv_app_badge':         (1201, 'APP'),
    'sv_save_entry':        (1202, 'Girişi kaydet'),
    'sv_back':              (1203, 'Geri'),
    'sv_no_entries':        (1204, 'Henüz durum girişi yok.'),
    'sv_unit_second':       (1205, 'Saniye'),
    'sv_unit_minute':       (1206, 'Dakika'),
    'sv_unit_hour':         (1207, 'Saat'),
    'sv_unit_day':          (1208, 'Gün'),
    'sv_loop_time_integer_error': (1209, 'Yalnızca tam sayılar — ondalık veya sembol olamaz'),
    'sv_loop_time_min_error':     (1210, 'Döngü süresi 12 saniyeden az olamaz'),
    'sv_activity_type':      (1211, 'Aktivite türü'),
    'sv_activity_playing':   (1212, 'Oynuyor'),
    'sv_activity_streaming': (1213, 'Yayın yapıyor'),
    'sv_activity_listening': (1214, 'Dinliyor'),
    'sv_activity_watching':  (1215, 'İzliyor'),
    'sv_activity_competing': (1216, 'Yarışıyor'),
    'sv_stream_url':          (1217, "Yayın URL'si"),
    'sv_stream_url_hint':     (1218, 'https://twitch.tv/... veya https://youtube.com/...'),
    'sv_stream_url_required': (1219, "Yayın durumu için yayın URL'si gereklidir"),
    'sv_stream_url_invalid':  (1220, 'Yalnızca Twitch veya YouTube bağlantılarına izin verilir'),
    'sv_help_note_title':     (1229, 'Notlar'),
    'sv_help_note_body':      (1230, "Değişikliklerin etkili olması biraz zaman alır. Bot çalışırken durum eklemek, "
                                      "düzenlemek veya silmek — ve varlığı açıp kapatmak — anında uygulanmaz. Bot "
                                      "önce mevcut listedeki döngüyü tamamlar, bu nedenle güncellemenizin görünmesi "
                                      "biraz zaman alabilir."),

    # ── Bot Oluştur — Yedekten içe aktar ───────────────────────────────
    'import_zip_btn':         (1221, 'Yedekten geri yükle'),
    'import_zip_disabled_hint': (1222, 'Önce bot adını ve geçerli bir token ayarlayın'),
    'import_zip_selected':    (1223, 'Seçilen yedek: {file_name}'),
    'import_zip_clear':       (1224, 'Kaldır'),
    'import_zip_invalid':     (1225, 'Bu bir bot yedek dosyasına benzemiyor'),
    'import_zip_pick_title':  (1226, 'Bir yedek ZIP seçin'),
    'import_zip_applied':     (1227, 'Bot oluşturuldu ve yedek geri yüklendi!'),
    'import_zip_failed':      (1228, 'Bot oluşturuldu, ancak yedeği geri yükleme başarısız oldu'),

    # ── Kaydetme geri bildirimi ────────────────────────────────────────
    'saved_successfully':     (1231, 'Başarıyla kaydedildi'),

    # ── Mobil Uyarı ─────────────────────────────────────────────────────
    'mobile_warn_title':      (1232, 'Arka Plan Çalıştırma Bildirimi'),
    'mobile_warn_body':       (1233, 'Botları mobil sistemlerde (yalnızca Android) çalıştırmak, sıkı arka plan sınırlarına tabidir.\n\n• En iyi durumda, bot arka planda yalnızca en fazla 6 saate kadar çalışabilir.\n• Cihaz ayarlarınızda Pil Optimizasyonunu devre dışı bırakmalısınız ("Sınırsız" olarak ayarlayın).\n• Bazı cihazlar botu küçültüldüğünde hemen askıya alabilir.\n\nBotları barındırma/sunucu/VPS veya benzeri yerlerde çalıştırma konusuna gelince, bu henüz desteklenmemektedir.'),

    # ── Komut Düzenleyici Sözdizimi Uyarısı ─────────────────────────────
    'syntax_warn_banner':     (1234, 'Renk modu etkin. Büyük dosyalar için (>2000 karakter), cihaz gecikmesini önlemek amacıyla renk modunu kapatın.'),
    'syntax_limit_refusal':   (1235, 'Renk modu açılamıyor: Performansı korumak için metin 2000 karakter sınırını aşıyor.'),
    'syntax_color_label':     (1236, 'Renk'),

    # ── Toplam Sayılar ──────────────────────────────────────────────────
    'total_bots_count':       (1237, 'Sahip olduğunuz toplam bot: {count}'),
    'total_vars_count':       (1238, 'Toplam değişken: {count}'),
    'total_cmds_count':       (1239, 'Toplam komut: {count}'),
    'total_wiki_count':       (1240, 'Sonuçlar: {count}'),

    # ── Wiki filtre sayfası (genişletilmiş) ─────────────────────────────
    'filter_title':          (1241, 'Kategoriler'),
    'reset':                 (1242, 'Sıfırla'),
    'close':                 (1243, 'Kapat'),
    'done':                  (1244, 'Bitti'),
    'clear_search':          (1245, 'Aramayı temizle'),
    'filter_tooltip':        (1246, 'Filtre'),
    'no_categories':         (1247, 'Henüz kategori yok'),
    'verify_token':          (1248, 'Tokenı Doğrula'),
    'verifying':             (1249, 'Doğrulanıyor...'),
    'token_valid':           (1250, 'Bağlantı başarılı! Token geçerli.'),
    'token_invalid':         (1251, 'Geçersiz Token veya bağlantı başarısız.'),
}
